### ISSUE TITLE
Request: Successful build on x86/x64

### ISSUE THREAD

**Issue by dlasher** [midwan/amiberry#131]
Hey there team,

Love Amiberry, love it.. have loaded it on 3 different PI, and have helped build a few more as retro gaming machines. Love it enough that I want to build a dedicated machine with a BIT more horsepower to run it. I have some spare x64 hardware, so I've gone through the exercise of DietPI, then RetroReplay, but I'm missing the most important part.. all the config I've copied from my Amiberry machines is written for the CLI options/etc of Amiberry. I need Amiberry!

So... I'm hoping that we can get a Makefile (and other appropriate bits) include for x86/x64 builds. Please?

thanks in advance.

**Comment by midwan** [comment]
Hi @dlasher 
Amiberry was designed to be ARM-specific from the beginning, since there are other options already for x86 platforms, but we had rather poor support for ARM.

It may be possible to make it compile on x86 also in the future, by adding the x86 JIT engine, etc. But at the moment, this is not a priority, as we have to work on fixing any bugs, implement some new features that are missing, improve compatibility and performance etc.

If we had more people on board, perhaps some could focus on separate things like this one, but unfortunately it's just a few of us at the moment. :)

**Comment by Voljega** [comment]
Sorry wanted to comlent this issue before : would it be possible to make odroid xu4 a target for compilation then ? It's ARM too and becoming popular quickly

**Comment by bspinner** [comment]
Can someone give a overview of what needs to be done for Odroid XU4 compatbility?
I took a look at the Makefile and it seems very RPi specific already. Is there still a chance to open it up for other ARM sbcs?
