### ISSUE TITLE
Black screen, fast sound on RPI2

### ISSUE THREAD

**Issue by fingertrouble** [midwan/amiberry#137]
I can't get Amiberry to work at all - I get the GUI, but either using the built-in settings or my ROMs - which work on UAE on my Mac - I just get a black screen. No hand, nothing. I've tried WB disks, one of my own demos from back in the day, etc. I get at best a jumbled 'too fast' sound playback, but nothing on the HDMI monitor.

I am using RPI Raspbian Stretch, I get problems with the dependencies as it complains:

Package libguichan-sdl-0.8.1-1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libguichan-sdl-0.8.1-1v5

I installed the replacement package...using the 2.1 binaries for RPI2. I'm guessing RPI2 won't be supported in future?

I have 128Mb split to the GPU, trying 256 and checking to see if the GL driver is loaded...

**Comment by CypherXG** [comment]
LOL. Turn off GL Driver

**Comment by HoraceAndTheSpider** [comment]
Yes there is every plan to support RPi2. I have it running on one myself.

**Comment by HoraceAndTheSpider** [comment]
@midwan has been doing some tests on Stretch also so may be able to comment if there are any issues there

**Comment by midwan** [comment]
@fingertrouble 
I've just started testing Stretch a few days ago, so far on the Pi 3 only.
I've been testing our latest development builds only, so perhaps there is a difference there also ;-)

I can say that the SDL1 version works perfectly fine, even without disabling the OpenGL driver (something which was necessary in Jessie). Just a default Stretch image, with the dependencies added (plus the dev packages so I could compile from source), compiled the latest from source and tested...

The Pi2 will still be supported, as well as the Pi Zero. I don't have a Pi1 to test with, but since they share the same CPU as the Zero, I think it should still work there as well.

If you want, I can share a beta binary with you so you can try with that and see what you get? Keep in mind that it will be from the latest dev version, so you'll need to add the dependencies for that as well (one lib and one file which goes in the data/ dir).

**Comment by HoraceAndTheSpider** [comment]
I have about 3 Pi 1's so I can do that test ;)

**Comment by fingertrouble** [comment]
Yes that would be good - the beta version. Thanks!

**Comment by fingertrouble** [comment]
@CypherXG 
"LOL. Turn off GL Driver
If you turn on GL you see only a black screen"

How am I supposed to know that? And why is it so funny?

Yes that fixed it, switching off GL Driver in raspi-config. Strange, pretty sure it was either on fake or none before, but it could have been switched on.

**Comment by fingertrouble** [comment]
Actually was having problems with Compton desktop using 200-300% CPU - eek - so switched back to the fake KMS driver. Amiberry works AND I'm not getting the CPU issue.

Sound is still mega glitchy though...sigh.

**Comment by midwan** [comment]
Update on this:
@fingertrouble the current "dev" branch has many bug fixes applied, could you please try with that and see if you find any problems?

Regarding Stretch:
- The SDL1 version runs normally under X, but if started from the console the GUI doesn't show. That's due to changes made in Stretch regarding the EGL library names, that SDL1 references. The emulation screen uses Dispmanx so it's not affected by that, as long as you don't use the KMS driver (works with legacy and FKMS).
- The SDL2 versions work fine, both from the console and under X. If you use the KMS driver, and build SDL2 from source with support for that, you can launch it from the console as well. There is also an SDL2 target with Dispmanx, to use that you'll need to be using the Legacy or FKMS driver instead.

Note that there is a known bug for now, when using SDL2 & KMS driver: The frame rate is lower than normal if you set the CPU speed to > 14MHz. This does not happen in any other target, only SDL2 with KMS.

**Comment by midwan** [comment]
@fingertrouble 
We now have SDL2 targets that use Dispmanx (like the SDL1 does), to get the best performance out of it until we find a way to optimize and make the SDL2/KMS combination as fast. You can make them using "PLATFORM=rpi3-sdl2-dispmanx" for example.

I believe that should address the immediate problem at least, so we can close this issue for now...
