### ISSUE TITLE
Quickstart options

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#155]
Hi,

 a few points regarding the quickstart menu.

- [x] When selecting a quickstart preset it also changes the Miscellaneous options. Could you prevent it from doing this so that the on screen drive lights etc. don't disappear when changing Model, like WinUAE.

- [x] If we are using a custom config and want to change to the quickstart preset that's already highlighted then we have to change to a different preset first for it to change the options and then back to the preset originally wanted. It would be better to have a 'Set configuration' button like WinUAE, so if we go to the Quickstart pane and want to change to the model that's already highlighted then just click the 'Set configuration' button.

- [x] @HoraceAndTheSpider It can't navigate through the Quickstart models using the D-Pad.

**Comment by HoraceAndTheSpider** [comment]
To mirror what was mentioned elsewhere: (future reference)

The changing of QuickStart model I investigated yesterday. It is nothing to do with the controller input ... you get the same problem when using the keyboard cursor keys.

This is to do with the navigation.cpp code and the handling of drop-downs and other GUI elements. I will be looking into it to see why certain gui elements differ from others , but as I say, it’s not specifically controller related.

**Comment by midwan** [comment]
The navigation bug has been fixed with ed876469c788cf6b02635fac7de2f12d5a04a39b and 6e87512c1544a51d4f143d45cbbf542fc24b2957

**Comment by midwan** [comment]
The Misc options (status Led) changing has been fixed also.

When selecting a Quickstart option, the default options are applied (followed by the target specific options). The Show Status LED from the Misc panel was incorrectly also modified.

That leaves the "Set Configuration" button which we could easily add also.

**Comment by blinkydoos** [comment]
I just moved these two posts here as they were in an unrelated thread that is closed anyway (just in case there are any changes). I also updated the first post.

> The Set Configuration re-applies the selected config, but the dropdown will also apply what you selected (same as WinUAE does in this respect). This is by-design. :)

> But the version of WinUAE that I have (v3.6.0 beta) it doesn't apply the chosen quickstart until you press the 'Set Configuration' button. There doesn't seem to be any point for the 'Set Configuration' button if it applies the settings anyway (probably WinUAE 3.5.0 and below which doesn't have the button like you showed).

**Comment by midwan** [comment]
@blinkydoos 
I believe that the role of the button, is to apply the settings "manually" if one wishes to do so. An example usage scenario would be the following:
- You have loaded a custom config already, perhaps you are already emulating as well. You enter the GUI. You want to apply the currently selected Quickstart menu.

Before, you'd have to change the dropdown option to something else, then switch it back to what you had in order to apply it. Now, you can just click the button.

Alternatively, selecting another option from the Dropdown would apply the settings of that option immediately. Otherwise, you'd have to do one extra click (select option from dropdown, then move to the Set Configuration button and click it), which makes the user experience worse.

I believe we should be aiming to make the user experience more streamlined and better, with less effort required to do want you want, where possible. Adding the button has helped in this direction (no need to click the dropdown twice), but let's not introduce the opposite (having to click the button always in order to apply a setting).

**Comment by blinkydoos** [comment]
OK, got ya. I'll close this.
