### ISSUE TITLE
ETA 2.5 final ?

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#157]
Please don't take this issue as pressuring or anything, I'm not that guy going on open sources repo to angrily ask thing :)

It's just as we are close to integrate Amiberry into the Recalbox distribution, I was wondering if 2.5 was close to be released in which case we would maybe wait some time, because the merging of the refactoring of the whole controller scheme by @HoraceAndTheSpider seems to mark a big step toward an even better amiberry !

So is it weeks or months ? Should we proceed on integration or wait a little ?

Also if we were to use the 2.1 version, the right branch to compile it is master right ?

Anyway, thank you all again for your awesome work on this emulator

**Comment by midwan** [comment]
@Voljega 
Thanks for the interest!
We're definitely close, but there's no hard deadline. A rough estimate would be a few more weeks (famous last words, I know), certainly not months away. If you could wait a bit longer, it would be great, since many things are improved compared to v2.1.
Basically the biggest part was merging in those changes from @HoraceAndTheSpider and now we need to clean up some minor glitches and polish some things up, test it a bit more, then package it up for release.

Hope that helps!

**Comment by Voljega** [comment]
Yeah clearly, thank you very much for the answer !
