### ISSUE TITLE
Latest dev version. Can't enter config menu

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#164]
Hi
I've tested your latest SDL2 Version of amiberry.
Installed all SDL2 Libs. Compiling works perfectly.
But when i start the Emu i cant enter the config menu. 
I tried it with default config and with my configs.

**Comment by midwan** [comment]
Which latest version did you try?
The latest one actively being worked on, is the "dev" branch.
"sdl1-dev", "sdl2-dev" are now older development versions, which will eventually be deleted since they have been merged into "dev". They are still around just in case we need to look at something, until we resolve all bugs in the dev.

There is also an older "sdl2" branch which is not currently updated. That will also be deleted once the "dev" reaches stable status and gets merged into master.

**Comment by CypherXG** [comment]
I use this version:
https://github.com/HoraceAndTheSpider/amiberry/tree/cca2253eaa8361cbca32ddd671635d0c754601e1
It starts good but i can not enter Menu

**Comment by midwan** [comment]
@CypherXG that is on a different repo, so it may not always be up to date with the latest "Dev" version here...

Regardless, I will assume you're using the SDL1 version? There is a known problem with that at the moment, which I'm looking at. It should be fixed over the next few days...
The SDL2 version does not have the same problem.

**Comment by CypherXG** [comment]
Yes i'm using the latest Version for SDL2
There no new updates to download.
I can compile it without errors, start the emulator, but only without Picasso mode without enter the Menu etc. 
When i use my config with Picasso Mode the Emu starts with the Kickstart screen and when it switch the Screenmode to Picasso i see only a black screen. Thats it. Then i must reset my Pi to enter again the Terminal. I always try to edit my config to change the menu key, same.

**Comment by midwan** [comment]
@CypherXG Are you using the SDL1 or SDL2 version?

What command did you use to build it?

The SDL1 has a known bug similar to what you describe, but the SDL2 one does not and works normally...

**Comment by blinkydoos** [comment]
I just tried to build the latest DEV SDL2 version but got an error -

```
 #include "SDL_image.h"
                       ^
compilation terminated.
<builtin>: recipe for target 'src/sdl/sdlimageloader.o' failed
make[1]: *** [src/sdl/sdlimageloader.o] Error 1
make[1]: Leaving directory '/home/pi/amiberry-dev/src/guisan'
Makefile:158: recipe for target 'guisan' failed
make: *** [guisan] Error 2

```
I followed all the instructions from here -
https://github.com/midwan/amiberry/wiki/Compile-SDL2-from-source
https://github.com/midwan/amiberry/tree/dev

and used -
make all PLATFORM=rpi3-sdl2

**Comment by midwan** [comment]
Maybe I missed something in the dependencies, I'll check it again. This indicates that SDL_image wasn't built/installed...

**Comment by midwan** [comment]
This should no longer be an issue now, as all related bugs have been fixed.
SDL2 dependencies need to be in place, otherwise some things might not work.
I've updated the Wiki to add a list of all the dependencies SDL2 installs on Stretch, if you would install "libsdl2-dev" (which is an older version and does not contain the rpi driver). That should help getting everything in place.
