### ISSUE TITLE
HDFs >2GB support missing

### ISSUE THREAD

**Issue by TuKo1982** [midwan/amiberry#20]
Uae4arm seems to miss support for more complexe HDF which contains more than partitions and files bigger than 2Gb.

**Comment by midwan** [comment]
Thanks for reporting this.
Any way to recreate it please? We'll need a way to know it works when it's fixed.

**Comment by TuKo1982** [comment]
Juste create an image of an Amiga harddisk or an UAE HDF wich his >2Gb and has multiple partitions.

**Comment by midwan** [comment]
Thanks, I'll try that.

**Comment by midwan** [comment]
Note to self: Now that the WinUAE 2.8.1 merge is nearly complete, check if that part of the code can be merged into the master/SDL2 branches

**Comment by ChoccyHobNob** [comment]
There doesn't appear to be any support for real RDB HDF files, only 'partition' HDF's.

**Comment by midwan** [comment]
@ChoccyHobNob 
Yes, that is the purpose of this issue actually :)
It's coming, it just takes some time to merge everything in, make sure it works, optimize it for ARM, etc.

**Comment by midwan** [comment]
Update: this still seems to be an issue with the current dev beta (v2.8b)

**Comment by rsn8887** [comment]
This comment from Toni Wilen might be relevant: http://eab.abime.net/showpost.php?p=1131223&postcount=12

```
2G limit comes from 32-bit filehandling support. (hardfile.c is really old and very basic)

- C-library fseek() and friends support only up to 2G. They need to be switched to 64-bit versions.
- Normal CMD_READ/CMD_WRITE can do up to 4G-1.
```

**Comment by midwan** [comment]
@rsn8887 
Thanks, I suspected something like that actually, but WinUAE seems to work with them (I created a 3GB hdf for testing this).

**Comment by midwan** [comment]
@AnalogHero 
Thanks for the report.

**Comment by c0d3h4x0r** [comment]
+1, I want this too!

**Comment by midwan** [comment]
I don't think this is possible under a 32-bit system, which we are running at the moment:

If you're on a 32-bit system, the largest possible single object in memory is 2GB-1byte (i.e. SSIZE_MAX). Per POSIX, the behavior of write for size arguments that cannot fit in `ssize_t` is not defined; this is because write returns type `ssize_t` and could not represent the number of bytes written if it were larger. Perhaps more importantly, it's dangerous for an implementation to allow objects so large that their size does not fit in `ptrdiff_t`, since that would create a situation where pointer arithmetic could invoke integer overflow and thus undefined behavior.

**Comment by midwan** [comment]
We can look into this again once we have AArch64 support, and it would only work there I'm afraid. Unless we discover some other way of course.

**Comment by midwan** [comment]
However, RDB support and multiple partitions do work (as long as the HDF is up to 2GB).
Just remember to place the filesystem handler (e.g. FastFileSystem, pfsaio, etc) in the `kickstarts` folder.

**Comment by midwan** [comment]
I actually found a way to implement this, so it's done in the current version on `master` :)

**Comment by njt1982** [comment]
> so it's done in the current version on master

Does this mean v2.24 onwards support >2Gb HDFs?

**Comment by midwan** [comment]
Yes, the current version (2.25) has been tested thoroughly with larger HDFs on multiple platforms.

**Comment by njt1982** [comment]
Thanks @midwan :)

**Comment by AnalogHero** [comment]
Tested it a while ago and works. No problem with sfs filessystem. Thanks for adding this feature!

**Comment by c0d3h4x0r** [comment]
Confirmed, this is now working on my end.  Thank you!!

**Comment by digitalMedic** [comment]
I am using the latest version of Amiberry (v3.0.11) and I cannot make a hard drive file greater 2GB.  I put the pfsaio file in the kickstarts folder and I can still only make a 2GB partition even though I can enter an amount greater 2GB.  It just stops at 2GBs.

**Comment by CypherXG** [comment]
Do you use new HDInsttool oder new HDToolBox?
Did you use the newest PFS3 (pfs3aio) from the Aminet?
For PFS3 did you enter a new DOSTypefor the Filesystem? 0x50445303 => AIO Direct SCSI or 0x53465305 => "Standard" PFS3:

<img width="767" alt="Anmerkung 2020-01-25 132302" src="https://user-images.githubusercontent.com/7895130/73121051-2e146200-3f76-11ea-8ae8-dcbe17d1c7a7.png">

Do you add the PFS3 Filesystem to the MBR? You must add the PFS Filesystem with your HD Install Tool:
<img width="767" alt="Anmerkung 2020-01-25 132302" src="https://user-images.githubusercontent.com/7895130/73121028-dfff5e80-3f75-11ea-920e-fbd9b9608ee1.png">

Do you enter the correct Mask for your Controller that you emulate (SCSI, IDE)? 0x50445303 => AIO Direct SCSI or 0x53465305 => "Standard" PFS3:

Did you use Google to find a solution:
http://eab.abime.net/showthread.php?t=64949

Best regards

**Comment by digitalMedic** [comment]
Hi, thanks for the reply.  I did all of those things.  I am quite versed in using the Amiga and using Amiga emulators.  I use WinUae all the time.  I thought it was odd to put the pfsaio in the kickstart ROM folder as I wasn't sure why, hit that is what was recommended on here by Midwan in the text above.  I am able to make a hdf bigger than 2GB on WinUae and ony real Amigas without a problem so I have done it often.  😊

I tried making a hdf using the 3.1.4 ROM and the 3.1.4 OS which automatically recognizes hard drives >4GB, but Amiberry still only sees 2GB max whether I make a hdf of 4GB or 8GB.  I tried using the UAE controller and the IDE controller in the hdf setup.  No matter what I do, the emulator only sees 2GB.  Even in the emulator hdf config section, a hdf greater than 2GB shows as 2GB only.

I would rather use a hdf instead of a directory, which I also know how to create, just personal preference I guess.

Thanks for the reply though.  😊
