### ISSUE TITLE
Keyboard bug after booting from UAE file

### ISSUE THREAD

**Issue by ghost** [midwan/amiberry#208]
As an example, if you set a A1200 quickstart and load the attached file. It says press HELP to switch NTSC/PAL. I pressed HELP and it automatically changed the resolution to 640x200 and was 60Hz according to the Status Line, but looking in the GUI, NTSC is not on. I switched it on and off again and resumed but it locked up with a black screen.

While in NTSC, pressing -

Z also presses SPACE at the same time
X also presses RETURN
2 also presses P
\ also presses the blank key between LEFT SHIFT and Z

When Amiberry came back from it's lock up, I switched Quickstart to A500 (PAL) but the keys still did what I showed above !

[Crack Intro Heimdall 2 (19xx)(Fairlight).zip](https://github.com/midwan/amiberry/files/1635756/Crack.Intro.Heimdall.2.19xx.Fairlight.zip)

**Comment by midwan** [comment]
The key behavior was supposed to be fixed, I'll check if we brought it back by mistake...

**Comment by midwan** [comment]
@blinkydoos 
The keyboard input bug is fixed already, I just double checked both SDL1 and SDL2 builds... Maybe you need to do a make clean first? :)

**Comment by blinkydoos** [comment]
Make clean ? I have been building SDL1 by following the instructions and typing `make all` for Pi 3, then replacing the amiberry file (and data folder if needed). What am I missing ?

**Comment by midwan** [comment]
@blinkydoos If you have an older build still in place, a "make clean" will remove old object files and the next "make" will rebuild them. If there are changes to header files, they are not picked up automatically if you just recompile on top of an older build ;-)

**Comment by blinkydoos** [comment]
When you say 'recompile on top of an older build', I always delete the old amiberry-dev folder before cloning the new one.

**Comment by midwan** [comment]
@blinkydoos OK, that's a bit... overkill :)
You could do a "git fetch && git pull" to get the latest changes only.
Or a "git fetch && git reset --hard origin/dev" if you want to wipe out any local changes and sync with the latest from the repo.

Anyway, I can't recreate the keyboard input problem you mentioned. This was fixed in an older commit, and I just tested several different version in different environments to make sure (Raspbian Stretch, Jessie, Retropie, RPI1, RPI3, SDL1, SDL2).

Please try the following after going in the directory you have cloned amiberry-dev:
- git fetch && git reset --hard origin/dev
- make -j 2 (if you want the RPI3-SDL1/Dispmanx version that is)

Then test again?

If you still get the problem with the keyboard, please let me know.

**Comment by blinkydoos** [comment]
I'll try this tomorrow and let you know.

**Comment by blinkydoos** [comment]
Just out of interest, what will those commands do compared to cloning the full fresh amiberry-dev directory and 'make all' ?

**Comment by midwan** [comment]
@blinkydoos they should do the same, this is just me being paranoid...

**Comment by blinkydoos** [comment]
I did some more testing and it seems it's nothing to do with NTSC. It only happens when I boot directly from one of Horace's UAE files made with his ConfigMaker. I select the UAE file which boots into the game, go to the GUI, change to a quickstart config, then in emulation the keys do what I showed above. I've attached one of his config's, maybe you could have a quick look to see if anything jumps out at you as to why this happens.

[Culprit Config.zip](https://github.com/midwan/amiberry/files/1638729/Culprit.Config.zip)

**Comment by midwan** [comment]
@blinkydoos Thanks for testing further!
I'll take a look at this tonight and see if I can recreate it.
Stay tuned... ;-)
