### ISSUE TITLE
Cannon Fodder mouse problems

### ISSUE THREAD

**Issue by Fable-Son** [midwan/amiberry#236]
In Cannon Fodder, when in "Input" I set Port 0 (Mouse) to my joypad, the game works perfektly. Eksept the exit (Select + Start) dosent work any more. Why is that? 
Tried to set the Mouse Stick 0 and 1 to left or right, when the Port 1 (Joystick) is set to my joypad. 
That won't make the mouse arrow move. But now my exit Works :D

**Comment by HoraceAndTheSpider** [comment]
This won’t work because you are trying to use a controller directly as a mouse, which therefore does not have retroarch mapping. (Since otherwise real nice may not be correctly supported)

You need to set the input to continue as a joystick (Not mouse) and then use the mouse stick option. (Left or right or both)

Potentially the application of this can be improved to correctly “interpret” a controller being used as a mouse, but for now, the above will work.

**Comment by Fable-Son** [comment]
I will try that. Thanks 😊

**Comment by midwan** [comment]
@Fable-Son 
When you get a chance to try it, could you please just mention if it works for you, so we can close the issue?

thanks!

**Comment by Fable-Son** [comment]
It might take a while. Ain't that often that I have a opportunity to play with my Pi3.
So you can just close it now,  if you like 😊

**Comment by midwan** [comment]
@Fable-Son 
Ok, closing it for now but feel free to report back if it's still an issue and we'll re-open it then.
