### ISSUE TITLE
SDL2 problem w

### ISSUE THREAD

**Issue by pawelcracow** [midwan/amiberry#237]
Hi.

When want to execute Amiberry SDL-2 I still have error: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory. How to resolve it ? thanks

**Comment by midwan** [comment]
This seems to be caused by an older version of libpng, which is included in Jessie.
Stretch includes a newer version of the library, and SDL2 seems to require that newer version.

Are you running on Jessie? If so, I'd recommend you upgrade to Stretch and it should work.
Alternatively, try the SDL1 version. Performance-wise, they are the same on the RPI.

**Comment by pawelcracow** [comment]
Yes. Im running from Retropie (latest udpate). SDL-1 working without problems.

**Comment by midwan** [comment]
RetroPie is still on Jessie, and so the best option for that system currently is the SDL1 + Dispmanx.
When RetroPie moves to Stretch in the future, things can change. :)
