### ISSUE TITLE
Up/down failed with Freebox pad

### ISSUE THREAD

**Issue by fredmutez** [midwan/amiberry#274]
### Expected behavior
I want to use my Freebox pad for Amiga games

### Actual behavior
Left and Right and Fire are OK
but Up and Down don't work

### Steps to reproduce the behavior
Plug the Freebox pad on Recalbox
Run any games playable with a joystick

Note the Freebox pad is OK with all the other system (nes,megadrive,mame,...)

**Comment by HoraceAndTheSpider** [comment]
Have you followed the wiki and is it detecting the retroarch layout?

https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers

**Comment by Voljega** [comment]
@fredmutez Realbox doesn't uses the latest version of amiberry, so if you have any questions about it, it's better to ask on Recalbox forum.

Your problem can't be corrected though, you'll have to wait for the integration of a newer version of amiberry on Recalbox

**Comment by HoraceAndTheSpider** [comment]
Thanks @voljega - I wasn’t aware of this with recallbox.

Can the binary not be manually updated? 

Closing the issue until the pad can be tested with the latest version.

**Comment by Voljega** [comment]
@HoraceAndTheSpider  no it's not that simple because we patched the binary for some paths (./data path, saves paths, screenshots path, etc...) and also we generate the entire conf dynamically when generating the uae and conf files based on the used controller and other things.
Furthermore, contraty to Retropie, Recalbox is a complete  very lightweight linux based on buildroot, so it's not always simple regarding binary and such.

So I have a lot of work to integrate the latest version and the whole controller rehaut, but right now the team is working on some other stuff, so this work has to wait

**Comment by fredmutez** [comment]
Thanks for your help
My another solution is to buy a new pad :) (8BitDo?)

**Comment by Voljega** [comment]
I really can't give you guarantee on the one that will work or not, all I can say is that xbox360 pad and ps3 pad are working (although for ps3 pad; left and right on analog stick aren't working, but dpad is ok)
