### ISSUE TITLE
Putty Squad AGA Slow

### ISSUE THREAD

**Issue by MontyMoleUK** [midwan/amiberry#278]
### Expected behavior
Should run at normal speed.
### Actual behavior
Quite a lot of slow down making the game unplayable.

**Comment by HoraceAndTheSpider** [comment]
Fast Copper option seems to fix the speed issue..

I do have some gfx corruption on the bottom of the title screen though

**Comment by midwan** [comment]
@MontyMoleUK 
The speed issue can be fixed with the Fast Copper option (in the Chipset Panel), as @HoraceAndTheSpider mentioned.

There is a glitch with the title screen, with some gfx corruption at the bottom, which I didn't see in WinUAE (so it's a glitch in Amiberry). However, that doesn't seem to affect anything else in the game, so I'd say it's a minor thing for now. It will probably get fixed as we continue to improve emulation accuracy with new updates.

Therefore I believe we can close this issue for now.
