### ISSUE TITLE
XU4: Problems loading CD32 roms through .uae

### ISSUE THREAD

**Issue by doidgy** [midwan/amiberry#306]
Hi, I am using an Odroid XU4 running ORA.

I am trying to load my cd32 roms by updating the .uae file with the different paths to the rom and kickstarts but without success. If I input the paths within amiberry itself they work without issues.

Updating the .uae files for .adf and .hdf roms run flawlessly (after paths are updated) it is just the cd32. 

Here is one .uae file (had to convert to txt file to upload) for a .hdf that works and a .uae for a cd32 which I have attempted to update but without success
[Beneath a Steel Sky (CD32).txt](https://github.com/midwan/amiberry/files/1928032/Beneath.a.Steel.Sky.CD32.txt)
[Brian Laras Cricket 96 [HDF].txt](https://github.com/midwan/amiberry/files/1928034/Brian.Laras.Cricket.96.HDF.txt)

I believe this is not an Amiberry issue but mistakes I am making with the paths, any help would be appreciated, thank you for your work.

**Comment by midwan** [comment]
@doidgy 
Thanks for the information. From what I can see, both config files are old (they contain "pandora" references, which have been removed from Amiberry since v2.1).

Generally in such cases we recommend to recreate those configs, as it's not only paths but other options that will not work (e.g. Custom Controls is no longer relevant, and we have other new options in the newer versions).

The easiest way to find out what went wrong, would be to create a new config for the same title, then compare the two config files for differences. Since the old one contains lots of deprecated options however, you'll find plenty of differences there.

**Comment by midwan** [comment]
@doidgy 
Yes, that's certainly a correct approach. I'm happy to see it worked for you.
Also, yes, you can safely upgrade Amiberry using the RetroPie built-in script.
