### ISSUE TITLE
For Online DB: Dynablaster WHDLoad booter fix

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#331]
### Expected behavior
Dynablaster WHDLoad LHA file to auto boot

### Actual behavior

Appears to hang on 'black screen' after the booter

### Steps to reproduce the behavior

Use default settings.

### Fix

Enable 'fast copper'

**Comment by Fantomas13** [comment]
Yes, but it doesn't work for me, if you save it in the UAE-Config file and then start with UAE. It has to be set, after the amiberry-logo disappears.

**Comment by Fantomas13** [comment]
Hello,

I recorded the problem on two videos.
They were made with Amiberry 2.21 and the ROM DynaBlaster_v1.2_0664, I renamed them into simple name, because I hoped to solve the problem.


The First video shows, that if i press  F12 after the amiberry logo and acivat Fast Copper, the game starts.
https://drive.google.com/open?id=16mhqw0s4mgnA4wTcD2aloL_JgXcW36HF

The next video shows the UAE-Config from the beginning. I saved it out from the F12 Menu in order to have the right settings. Only fast copper is activated from the beginning. But the game doesn't start.

https://drive.google.com/file/d/10im0pnuRkpoVjW01nZQi9YIK774YHUW3/view

Another issue, that  I noticed was, that any other game, that i start I can change the display resolution, instead of Dynablaster. There I get a black screen and that was it.

Thank you

**Comment by Fantomas13** [comment]
Hello, 

I wanted to ask, if any progress is made?

Thx

**Comment by bizzar721** [comment]
@HoraceAndTheSpider  @Fantomas13 Just found that if you hold down both mouse buttons while loading (immediately after runcommand loading screen/before Amiberry logo) it will bring up "Amiga Early Startup Control".   Select "Display Options" then select NTSC. Then Select "Boot" and your golden.

**Comment by bizzar721** [comment]
Instead of the convoluted way of enabling NTSC, I instead started DynaBlaster, then opened the Amiberry menu when I got to the black screen.  I went to chipset and selected the NTSC checkbox, then enabled Fast Copper as well. (there was a graphical glitch on the top of screen that Fast Copper seems to have fixed).

I also set the Display settings to Height of 240 and Vertical Offset at -11 to get the screen to not be cut off.

I saved the config for this game to automatically load those settings.  I searched the config file to see what was needed to add to WHDload_db. I assumed `ntsc=true `but it `ntsc=true` didn't do anything.

**Comment by HoraceAndTheSpider** [comment]
confirmed, and fixable with an XML change. This will be included in the testing before rolling out the booter update.

**Comment by Fantomas13** [comment]
Hello,

didn't show up for a longer time, but still interested.

What does "fixed in HATS" mean and what do I have to do now, to fix dynablaster to get it running?
Does ist mean the whd-load file for each game?

**Comment by HoraceAndTheSpider** [comment]
All changes since will have filtered down from the HoraceAndTheSpider (HATS) branch into the main branch.

I assume this is now working on the latest release version

**Comment by Fantomas13** [comment]
So should i try an amiberry Installation from source? 

Today I updated from binary and downloaded the newest dynablaster.lha from feburary 2019. But it didn't work

**Comment by HoraceAndTheSpider** [comment]
any file called simply 'dynablaster.lha' isnt going to be supported, because its not in the RetroPlay format. 

If you have downloaded from whdload.de, then that is only the installer. 

The latest RetroPlay file for this game appears to be `DynaBlaster_v1.4_0664`

**Comment by Fantomas13** [comment]
Good morning,

ok, I downloaded this version. Didn't word. Then I configured the whd-file like:

;PRIMARY_CONTROL=MOUSE/JOYSTICK
;PORT0=JOY
;PORT1=JOY
FAST_COPPER=TRUE
;CPU=68000/68010/68020/68040
;BLITTER=NORMAL/WAIT/IMMEDIATE
;CHIPSET=OCS/ECS/AGA
;JIT=TRUE
;CPU_COMPATIBLE=TRUE
SCREEN_HEIGHT=240
SCREEN_Y_OFFSET=-11
;LINE_DOUBLING=TRUE
NTSC=TRUE
;SPRITES=NONE/PLAYFIELD/SPRITES/FULL
;FAST_RAM=1/2/4/8
;Z3_RAM=16/32/64/128
;CLOCK=7/14/28/MAX

didn't work too. Then I pressed F12 and saw, that these setting weren't made. So I activated them. Dynablaster starts, but much too fast. :-D

**Comment by Fantomas13** [comment]
No further suggestions/ solutions?

It is a really good game, which i would like to have on my Pi3 Amiberry :-D

**Comment by HoraceAndTheSpider** [comment]
'.whd' files are not supported anymore - this should work 'out of the box' - i will have a look over the weekend.

**Comment by Fantomas13** [comment]
Is it possible to set individual settings like with the .whd-files?
I would like to adjust resolution for some games.

Do you have a solution?

**Comment by HoraceAndTheSpider** [comment]
just change the setting in a main menu and use the normal 'save config' option.  The .uae file will be loaded when you boot the game.

Unfortunately my main testing Pi has a corrupt SD card atm and i havent had time to fix it, so i cant do any testing at present.

**Comment by Fantomas13** [comment]
@HoraceAndTheSpider Thank you for the answer. Perhaps there will be a solution for dynablaster in the near future. It is the last game i want to add to have wonderful moments with the amiga version.
