### ISSUE TITLE
Amiberry v2.21 on RetroPie running on Raspberry Pi 3 B+ has tons of bugs

### ISSUE THREAD

**Issue by troydm** [midwan/amiberry#340]
Following are the issues I have with Amiberry v2.21 running under latest Raspbian Raspberry Pi 3 B+: 
1) only JIT + Turbo works, other JIT settings make Workbench 3.1 not  boot at all
2) Restart key resets all settings instead of restarting machine
3) Keyboard input is misbehaving, e key in Shell prints Error Command instead of just typing e character and enter key instead of entering command prints additional p character which unless removed by pressing backspace doesn't executes command at all, it's all weird as if some other keycodes are sent instead of correct ones

Amiberry is compiled against SDL1 installed from RetroPie setup using Install from source
None of those issues are present in uae4arm as the same hard drive with Workbench 3.1 works fine running on UAE4Arm.

Running Amiberry standalone from console instead of starting from ES doesn't fixes keyboard issues so I assume keyboard issues are SDL1 related

**Comment by midwan** [comment]
@troydm 

1. I haven't heard about such a problem before, and so far I haven't been able to recreate this. Could you provide more details on your emulated environment please? Are you trying with a WB3.1 ADF image or a virtual HDD? What ROMs are you testing with? What settings did you use in the emulator (did you try a Quickstart option?)

2. I think you're confusing Restart with Reset? Restart is supposed to reset all settings, as it's restarting the whole emulator with the defaults. Reset will perform an in-emulator reset (like holding LAmiga + RAmiga + Ctrl). This is identical to what WinUAE does with the function of the same name.

3. This is by design if you have Port 1 set to emulate a joystick using the keyboard. The extra keys are used in games that way, if you want to avoid this, you can set Port 1 to be either None or a real gamepad/joystick device (if you have one connected).

**Comment by CypherXG** [comment]
1.
WB 3.1 works with all Settings, sry. I used WB 3.1 before a long time.
Here you can see my Amiga Config with turbo setting...
![screenshot](https://user-images.githubusercontent.com/7895130/41819368-845f15d6-77bf-11e8-901c-0c48bc3ddb68.png)
Booting from HDF File formatted in PFS3.
![screenshot](https://user-images.githubusercontent.com/7895130/41819383-b9a42e48-77bf-11e8-9481-89b3e6373ed9.png)
With JIT or without does no matter.
Booting without JIT and like an A500 7Mhz 512kB Chip/512kB Slowram works also without any Problem.
![screenshot](https://user-images.githubusercontent.com/7895130/41819555-74e547e4-77c2-11e8-8c32-ca7a9f68c694.png)
Also a A1200 is emulated perfectly.Ok its a little bit faster.. but it's ok
![screenshot](https://user-images.githubusercontent.com/7895130/41819574-e6f0f7ac-77c2-11e8-97b6-e8a10131eb53.png)

2.
Yes, restart can be compared to a cold start (straight on) of a computer, while a restart simply corresponds to the key combination LAmiga + RAmiga + Ctrl.

3.
Haha, I had that problem too.
Was actually the keyboard set as a joystick.
Sure that this does not work when typing

**Comment by midwan** [comment]
@troydm 
Since you mentioned "uae4arm", please make sure you're not using a common config file between the emulators? That might cause problems in your tests as several options are different and uae4arm has bugs related to the config file generation, that causes duplicate lines to be inserted sometimes.

Also, the `adfdir.conf` file is slightly different and should not be shared between the emulators. We've added some extra options there.

Ideally you should have each emulator use its own set of config files.

**Comment by troydm** [comment]
Thank you guys for such comprehensive replies, I think we can close this issue

1) After playing with settings it seems that I can't reproduce the issue I had, probably it was related to uae4arm as initially I've tried booting workspace after fresh install to see if it has difference in performance and probably clicked save configuration from under uae4arm couple of times before trying amiberry again. But now everything works correctly and all is good. also JIT+Turbo compared to JIT+Fastest has huge perfomance difference in SysInfo of 13Mflops vs 2-3Mflops, I'm not sure if it's intentional or not.

2) I've checked WinUAE again just to be entirely sure if I was right or not and under Windows pressing Restart in WinUAE doesn't removes configuration or ejects any attached hdd/cpu settings/rom/ram and just resets machine however under AmiBerry it resets all settings to their default values so I assume it's expected behaviour and I was under false pretence of expecting it to behave same as in WinUAE

3) Thanks alot, I didn't knew this was the issue so now everything works correctly
