### ISSUE TITLE
[Question] ReWrite WHDLoad Booter in proper code instead of AMOS ?

### ISSUE THREAD

**Issue by SaucySarah** [midwan/amiberry#345]
@midwan Your emulator is almost brilliant. This is only a question at the moment so please don't attack me for it ! I have been trying the WHDLoad bolt-on in Amiberry, mostly loading the LHA demos to watch/listen to. The booter is really slow before it even starts to load the files. I tried loading the ADF version and it booted a lot quicker ! There seem to be a lot of pauses in the Boot routine and plus the slow AMOS language on top of the loading time. I was also pointed to another booter on the EAB forums and that also runs a lot quicker when loading HDFs but you need to use a mouse to select. The AMOS booter does boot quicker on the second boot but you don't see any of the WHDLoad options (like cheats, skip intro etc.) and sometimes you'll find a game/demo that isn't worth booting again anyway ! A red error also keeps displaying, something about a Patch ?

So after all that, do you have any plans to rewrite this into proper code instead of using an AMOS program ? (Something like the way FSUAE emulator does it which is fast and shows the WHDLoad Splash screen everytime). Thanks for all your hard work on Amiberry in general.

**Comment by HoraceAndTheSpider** [comment]
Hi @SaucySarah 

The WHDLoad booter is coded by myself, rather than @midwan.

The reasons for the pauses in the boot routine are due to the system scanning for many possible iterations of files, double checking for the presence of kickstarts etc. 

Yes it is writen in AMOS, but it is not AMOS that makes it slow! It is only CLI / Command Line activity, and all the AMOS code is compiled (AMOS would be slower if we were writing blitter objects etc, but not for something like this)

I am not planning to reimplement it any other way, because i have big concerns about compatibility - I have (at the moment) chosen to keep it Amiga-side (which is ultimately what makes it slower) but makes the system only use what files are available inside the Amiga OS (other solutions will need to either read LHA files directly, or, like FS-UAE unpack them, which is not a preference as this make need adjustments for cross-system compatibility)

I feel this is a small 'price' to pay when the second-load is as quick as the system will allow. 
```
does boot script exist?
yes. 
load whdload slave
```
It is a deliberate preference for the 'fast load' not to show the WHDLoad splash again. And the Amiberry splash is multi-tasked so that it does not affect the load time (it is shown whilst the PRELOAD process takes place.)


All of the WHDLoad options can be accessed as long as the slave has been updated to  include the V17+ options inside the slave header, but yes, only from the 'slow' menu. 

See the wiki here:
https://github.com/midwan/amiberry/wiki/Using-Amiberry-WHDBooter-with-RetroPie-(Step-4)

You will find one of the pictures shows the 'second fire, or space, for custom options' 

The SetPatch warning can be ignored - this file was removed due to the 'copyright' of the Setpatch program still being held, but does not affect performance.

The only way it may be made quicker, is for some kind of 'amiberry created default' for the auto-startup files, which is something i may consider when we have the online database up and running. 

However, changes of CUSTOM options or similar will still use the existing booter.



Hope this helps answer everything.

**Comment by HoraceAndTheSpider** [comment]
Not sure what you mean about style... I’ve contributed to other areas of Amiberry, but hey ho. 


Whd slave Options should be found from looking at the WHDLoad website - the solution which gives the fastest possible load time (which you are asking for) cannot, by definition, also provide you with the whd splash options on bootup, so what you get now is the best of both - fast loading 99% time, options if you want them. 

The Setpatch warning will be removed on a future version, but as it has no effect, it’s hardly a priority. It’s not an error, just a notification. 

Using more workbench files, supplied by the user, is a big no-no for us. We want this solution to work “out of the box” as far as possible - the target userbase for Pi Gaming isn’t versed in the world of Amiga and the use of the free alternative (Aros) files already does this for us without complicating matters further. 


Copying the fs-uae route 100% is a lot of work for not much gain. As I said we want to avoid the unpacking of files like fs-uae does. It’s my favourite Amiga emulator but it is targeted at a different host machine and audience. 

Hope this helps explain the position. It’s somethign we discussed at length many months ago, and this was the best solution that achieved our aims (for now). 

There will be improvements i have planned, and hope you enjoy them.

**Comment by SaucySarah** [comment]
Just a note for when you get back to this. I don't see any need for that horrendous Amiberry picture ! It looks like it has been lasso cut from a thumbnail. It was obviously catered for a handheld device where you wouldn't notice the quality but for the majority of us that use TVs/Monitors it makes the place look untidy so to speak (no offence). I think we all know that we are using Amiberry! Anyway, this logo that you added increases the loading time by over 10 seconds ! The next screen that has the setpatch error clearly has a pause inserted as well, probably for your website plug. I think this can be sped up. Hopefully you will do something about this to at least halve the boot time, assuming you are never going to get rid of AMOS.

Many thanks.

**Comment by HoraceAndTheSpider** [comment]
That logo does not increase load time by 10 seconds. As i have already stated it is multitasked.

All games start/load faster than ADFs once the auto-boot script has been created.

**Comment by SaucySarah** [comment]
So what exactly is it doing for 10+ seconds while the logo is displayed (on 1st and subsequent boots) ? It seems like it does one thing then waits x seconds, then the next screen comes up then waits x seconds. I was pointed to a different WHDLoad boot program (but it requires a mouse to progress) and his program boots at least twice as fast as yours so it makes no sense when you say yours is "multitasking".  This makes me think it would be a lot quicker if it wasn't in AMOS. If he can do it, maybe you could too, or not. 

This is all meant in a friendly manner as text can be interpreted in different ways ! 

P.S. Is the RED Amiga boiing ball in the Amiberry logo supposed to be changing colours ? Shock !! Sacrilege !

**Comment by HoraceAndTheSpider** [comment]
> So what exactly is it doing for 10+ seconds while the logo is displayed (on 1st and subsequent boots) ? It seems like it does one thing then waits x seconds, then the next screen comes up then waits x seconds. 

When the booter is running it's 'long' load, it is scanning for all available slave files recursively. It is also reading header data from the WHDLoad slave once selected, allowing for the CUSTOM settings menu, generating the auto-startup, checking for available kickstart files; various bits and pieces. 
There will be some small waits in there, yes, to ensure any writing of files is complete. I'd favour that over something unreliable for the sake of few moments extra on the first load.

> I was pointed to a different WHDLoad boot program (but it requires a mouse to progress) and his program boots at least twice as fast as yours so it makes no sense when you say yours is "multitasking". 

Yes it is multitasking when displaying the booter - the program is running whilst WHDLoad is caching data. Even the emulated CPU speed will affect the boot time, along with the size of the game which requires preloading.

I have no idea what the other persons booter does, and i'm not going to comment on what the difference are likely to be; but it wont be a result of it being AMOS based which seems to be your focus here. You are free to swap the booter zip file with any other you prefer, or you can simply change out the Amiberry ball logo file if you have issues with it. 

> This makes me think it would be a lot quicker if it wasn't in AMOS. If he can do it, maybe you could too, or not.

Not sure what "or not"  is meant to mean. I've explained previously I will look at some streamlining, but that since it only affects the first load (and other, host-side options may become available) it isn't high on the priority list.


> This is all meant in a friendly manner as text can be interpreted in different ways !

I'm afraid to say it doesnt come across that way, but i have become accustomed to it working on this scene. Suffice to say it doesn't exactly act as a motivator. 

I've already said, the feedback is noted, i will look into streamlining the speed at a future time.

**Comment by midwan** [comment]
I think this issue has been covered now.

There are no immediate plans to replace the Booter with something else, but we will look into improving the performance of it, in the future.
