### ISSUE TITLE
Nitro Boost Challenge, plays slow

### ISSUE THREAD

**Issue by vretro** [midwan/amiberry#348]
Hi team,
The game “Nitro Boost Challenge” plays really slowly using a default A500 configuration. This game should work as expected on an A500 configuration. Proper play speed can be seen from the following video: https://archive.org/details/Amiga_500_Longplay_121_Nitro_Boost_Challenge

Thank you

**Comment by midwan** [comment]
@vretro 
Have you tried changing any configuration options? E.g. Fast Copper, Immediate Blitter, etc?

**Comment by midwan** [comment]
This works normally in `dev` with the following setup:
CPU Model: 020
CPU speed: 14Mhz

I also turned on Immediate Blits and Fast copper, but I'm not sure if those made much of a difference (the CPU speed did most of it).

@HoraceAndTheSpider 
The WHDLoad_db.xml for this title would need to be updated, as beside the above settings it also set my "keyboard as joystick" setting to Parallel Port 1, instead of Game Port. 
The filename I used was: `NitroBoostChallenge_v0.3.lha`
