### ISSUE TITLE
Control problem with some games

### ISSUE THREAD

**Issue by retrorangepi** [midwan/amiberry#371]

**Comment by retrorangepi** [comment]
Hi to all and thank you in advance.
I've found xbox 360 control problems with some games (B-C Kid, Ruff n' Tumble and Superfrog). If I press A button (green button) in the joypad during the game, the game quit and the return in the main screen. How is possible?

**Comment by midwan** [comment]
@retrorangepi 
I haven't seen this problem so far, and it does sound strange.
Are you running this on OrangePi? I need some details to try and recreate it.

**Comment by midwan** [comment]
@retrorangepi 
Could you please provide some more details on this, in order to try and recreate it?
Which version of Amiberry did you run?
Did you use a saved config? If so, could you attach it here please?
Did you use the ADF version of the games, or some other method (e.g. HDF, WHDLoad?)
Is this happening only with this specific controller? What about keyboard as a Joystick?

**Comment by midwan** [comment]
@retrorangepi 
Ping! Need some feedback on this, if we are to move it forward, please.
