### ISSUE TITLE
Mortal Kombat 2 - Controller Configuration

### ISSUE THREAD

**Issue by Fantomas13** [midwan/amiberry#396]
**Describe the bug**
You can not be Controller No 1 in Game if you are playing alone, no matter what you do.
I tested everything with the mortal kombat 2.whd-file to with different settings with different versions of the game

**To Reproduce**
1. Start Mortal Kombat 2 in with Amiberry
2. when the logo appears and you can choose between "Start" and "Options", you have activated only one Controller,  you always choose as Player 2.

**Expected behavior**
You choose as player one

**Screenshots**

**Raspberry Pi 3 B+:**
 - OS: retropie
 - Version retropie 4.4 , newest amiberry

**Comment by HoraceAndTheSpider** [comment]
The choice of controller number is handled by the input panel. Controller “1” (as designated in game) is usually port 1 (rather than port zero).

You can also change which of your local “host” controllers is used first for WHDLoad by changing the hostprefs file - details contained in the site wiki under the WHDLoad booter section

**Comment by midwan** [comment]
As @HoraceAndTheSpider mentioned above, this is a configuration issue and not a bug in the emulator. :)
