### ISSUE TITLE
Is it possible to move the whdboot/save-data folder?

### ISSUE THREAD

**Issue by Shawson** [midwan/amiberry#397]
Running AmiBerry under emulationstation (Using retropie (for Odroid in my example)) with USB Storage enabled (so rom's running from a USB external HDD) is it possible to move the whdboot/save-data and whdboot/game-data folder locations to also run from the hdd so if i upgrade the system these are not affected?  Is this something that is already supports and I've just not noticed?

**Comment by HoraceAndTheSpider** [comment]
RetroPie already handles these folders with symlInks so there is no reason you should not be able to do the same with odroid

**Comment by midwan** [comment]
@Shawson as @HoraceAndTheSpider already mentioned, you should be able to move the directory anywhere you want and create a symlink in its place.

Let me know if it doesn't work for you, and we can revisit this. Closing it for now.

**Comment by solskogen** [comment]
I tend to agree with the OP on this. It should be a option in the gui. For
instance where you choose paths for kickstarts.

**Comment by HoraceAndTheSpider** [comment]
There is no point in me adding this at present as the WHDLoad booting is going to change for the better.

Game-Data is text files provided with or made by the emulator so I feel it is fitting they stay with the emulator files. There is some renaming needed though because the booter will add support for more than just LHA files. 

Save-data i concur shoukd probably have an option to be moved, and I will consider how this is done in future. Savestates should really be in the same location.

**Comment by Shawson** [comment]
Ok thanks guys!  So I'll wait it out until the WHDLoad change!  Any details or a sneak peek on what's changing with it?

**Comment by HoraceAndTheSpider** [comment]
In short, gui and more in-emulator control of how the booter works.
