### ISSUE TITLE
WHDLOAD autoconfig is set to an amiga 600 with ecs by default

### ISSUE THREAD

**Issue by Mangaclub** [midwan/amiberry#398]
I compiled Amiberry from source on my Retropie - Raspberry Pi 3 a few days ago. 
Whenever i start to setup a new whdload game (wich works generally fine btw) amiberry starts with a Amiga system setup to be a A600 with kickstart 3.0 and ECS chipset. This will prevent any aga games to work there. 
Where do i set the default machine configuration for WHDload games? I guess there must be some uae file somewhere ?
(i start whd load games with the a1200 amiberry config in retropie but that seems to be ignored)

**Comment by HoraceAndTheSpider** [comment]
There’s an XML agile included with the source. WHDLoad_db.xml

You cannot start WHDLoad games from inside the Config At present, only command line, which will check the above file.

Hope that helps.

**Comment by HoraceAndTheSpider** [comment]
If it is not in the XML file, it means it has not been scanned for validation (something that now happens every few days) so in essence those renamed files are not “supported”. 

ECS is used as the first selected mode, but probably the file should not load at all. 

Otherwise you could mount any LHA file (an archive from Aminet for example), rename it, and potentially cause confusion, leading to bad error reports etc.

For the sanity of the devs, it is best to simply state that anything not in the XML is not supported. If the settings for a supported file are wrong however, they should be reported here for correction. 

The files which are supported come from the commonly distributed “RetroPlay” WHDLoad packs, which we are now syncing with every few days - there will be added functionality to ensure regular access for the updated version of this XML when the booter is next updated. 

I will also be looking at how the file can be detected by SHA1 which will allow renaming of the files, but still the file content will need to be as distributed.

**Comment by HoraceAndTheSpider** [comment]
Also i disagree re: WHDLoad taking care of chipset matters, as some games (especially older slaves) need the setting to have a more accurate speed for example, and since Amiberry targets low-spec ARM devices we should always look to use the lowest possible setting for each game (unless there is a performance gain otherwise)

**Comment by Mangaclub** [comment]
fair enought, thanks though for pointing me in the right direction. i had been using those whd load archives from RetroPlay and just renamed them for scraping reasons so the scrapers recognise the name better.

**Comment by HoraceAndTheSpider** [comment]
No problem. As I said, SHA1 detection is planned to solve that. 

If you are scraping with Skyscraper then the XML we produce for Amiberry is shared with the author, and generates scraping links direct to the openretro site.

Anything missing after that (which isn’t much) would be good to report via OpenRetro so we can ensure all the entries are on there :)
