### ISSUE TITLE
Clock is running too fast or too slow

### ISSUE THREAD

**Issue by IRoN-cP** [midwan/amiberry#411]
I use Amiberry for my BBS. There it is very important for me that the time is working properly.
On every one of my Raspberry (2 or 3) and every kind of Workbench (3.1, 3.5 and 3.9) the time is running too fast. It does not matter which distribution is active in the background, be it Amibian, Dietpi or your own Armbian distro.
On my Odroid XU4 and my Tinker board the time is running too slow. If I load this hdf in Winuae I have no time problems, there it runs accurately.

**Comment by midwan** [comment]
@IRoN-cP 
This might be related to the timing settings, since those are different between the RPI and Tinkerboard.
Luckily, starting with this version of Amiberry, those are configurable without the need to re-compile.

Open the file from Amiberry's directory: `conf/amiberry.conf` and you'll find a few related lines there:
`speedup_cycles_jit_pal`
`speedup_cycles_jit_ntsc`
`speedup_cycles_nonjit`
`speedup_timelimit_jit`
`speedup_timelimit_nonjit`

Try experimenting with the values there to see if it helps - use small changes and restart the emulator after a change in the file.

You should of course change the options related to your environment (e.g. PAL or NTSC, JIT or NonJIT).

For reference, here are the default values we used for both platforms (Tinker and RPI):

For the Tinkerboard, XU4 and other faster than RPI platforms:
```
speedup_cycles_jit_pal = 18000;
speedup_cycles_jit_ntsc = 15000;
speedup_cycles_nonjit = 1024;
speedup_timelimit_jit = -10000;
speedup_timelimit_nonjit = -960;
```

For RPI or similar performance boards:
```
speedup_cycles_jit_pal = 10000;
speedup_cycles_jit_ntsc = 6667;
speedup_cycles_nonjit = 256;
speedup_timelimit_jit = -5000;
speedup_timelimit_nonjit = -5000;
```

**Comment by tonioni** [comment]
CPU speed shouldn't affect timers. Does similar time speed difference also happen in WinUAE if you

1) Tick "Genlock connected" in Chipset panel? Old UAE versions cause Amiga OS to incorrectly detect genlock which will change OS timer behavior.
or
2) Change Advanced Chipset panel CIA-A TOD Clock Source. (Vertical Sync <> Power Supply 50Hz)?. This may be configured differently or does not exist in older UAE ports ("Big box" Amigas have Power Supply tick signal). This also changes OS timer behavior.

**Comment by midwan** [comment]
@IRoN-cP 
Also, might be worth giving a try to the `dev` branch version.
The `custom.cpp` code there is merged from the latest WinUAE with a lot of improvements, and although the performance is lower than what we have in `master` for now (until we find a way to optimize it), it might be OK for your needs.

**Comment by midwan** [comment]
@IRoN-cP 
Any update regarding this?

**Comment by midwan** [comment]
Closing this due to lack of feedback for now.
