### ISSUE TITLE
Barbarian_v1.1_Palace_1784 - Guru Meditation using stock database xml

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#424]
Hey guys,
I just tried to play the Barbarian game but I just get to the Guru Meditation screen.
Very strange because I was so sure I did try it and that it worked some week or so ago. (but then I have been up very late for many nights testing the emulator and configuring my retropie, and tiredness can have some interesting effects :) )

After doing a few tests I could get it working by doing either of the following (not both at the same time):
Test 1: Set ROM to 3.1 (A500,A600,A2000) rev 40.63 INSTEAD of 2.05 (A600HD) 37.350
Test 2: Set 'More Compatible' to False instead of True.

In both cases I can run the game and it plays at the same speed. Not played it extensively to verify if any solution is better than the other, but so far they seem to behave in the same way.

Is this a configuration issue to be corrected in the xml file or am I going mad?
I definitely have not made any custom configuration for this game or the emulator itself besides adding scanlines

**Comment by HoraceAndTheSpider** [comment]
the 68000 mode will only be compatible with the a600 kickstart. the booter does a check for this when loading, and if it isnt available defaults back to the original, so you will see the speed return to the 'faster' mode.

The problem you are having is more likely related to the use of the alternative AROS commands  which are apparently not 68000 compatible. This is fixed by the new booter solution.  See #417 and #357  for which this is effectively a duplicate.

**Comment by RetroD** [comment]
Awesome! Is the update actually live? I. E. I can update from source in retropie to get it?

**Comment by HoraceAndTheSpider** [comment]
I will be merging it into a new branch tonight, so it can be tested before merging into the master branch.
