### ISSUE TITLE
zip support when used via retropie?

### ISSUE THREAD

**Issue by fuzzy76** [midwan/amiberry#443]
It's very unclear why whdload via zip isn't supported, and I have a huge library of whdload games... in zip format. :-/ What would have to happen in order to support this?

**Comment by midwan** [comment]
@fuzzy76 
Amiberry will work just fine with ZIP files also. This is a limitation of RetroPie currently, which assumes that ZIP files are ADFs and nothing else, so it uses a different command line argument when launching Amiberry...

**Comment by HoraceAndTheSpider** [comment]
The distributed WHDLoad files in zip format are not only out of date, but often have errors due to the fact they are compressed via windows/non-Amiga systems. It was due to this that the makers of those packs switched to Amiga-side compression only (LHA). 

I won’t be adding support for them to the xml - partly because I don’t have copies of them for scanning, but mostly becuase of the above two reasons - they are no longer included in distribution packs.
