### ISSUE TITLE
2 missing dependencies for DietPi in the Guide

### ISSUE THREAD

**Issue by ProfDrLuigi** [midwan/amiberry#449]
There is something missing in the Howto to compile amiberry for RPi:

`sudo apt-get libraspberrypi-dev raspberrypi-kernel-headers`

**Comment by midwan** [comment]
@ProfDrLuigi 
On which distro?
You shouldn't need those on a normal Raspbian-based distro...

**Comment by ProfDrLuigi** [comment]
DietPi

Am 14. März 2019 9:48:46 nachm. schrieb Dimitris Panokostas 
<notifications@github.com>:

**Comment by midwan** [comment]
@ProfDrLuigi 
How did you try to install it? Did you use the "official" method with `dietpi-software` or did you try to install everything yourself from scratch?

The option to install Amiberry from `dietpi-software` should include all dependencies for DietPi, which is why there was no need to mention extra libraries that are deployed in standard Raspbian distros otherwise (DietPi is focused on minimal deployment, so some things are not there until you request them).

**Comment by ProfDrLuigi** [comment]
I tried to compile everything from scratch.
Ok nice to know that there is a Dietpi option.

**Comment by midwan** [comment]
@ProfDrLuigi 
No problem. Feel free to get back if you run into any issues :)

PS: DietPi includes not only an option to install Amiberry from it's own menu, but also an option to have it start up automatically at boot. ;-)
