### ISSUE TITLE
XDG_RUNTIME_DIR not set in the environment

### ISSUE THREAD

**Issue by matenkoH** [midwan/amiberry#453]
Hello,
I would like to run Amiberry 2.25 on Odroid-XU4 platform with DietPi 6.21.1 installed on it. I followed the installation guide on this wiki and compiled SDL2 for xu4 platform, after that installed Amiberry also as per guide. After all is set when I trigger run.sh I got following error:

`error: XDG_RUNTIME_DIR not set in the environment.`

Any ideas where could be the problem?
Thank you.

**Comment by midwan** [comment]
@matenkoH 
Hm, I think that sounds like a DietPi-specific issue rather than an Amiberry one.

@Fourdee - do you have any suggestions? Should this be opened on DietPi's repo instead?

**Comment by midwan** [comment]
Some related answers here: https://askubuntu.com/questions/872792/what-is-xdg-runtime-dir
and here: https://serverfault.com/questions/388840/good-default-for-xdg-runtime-dir

Either way, this is related to the distro and not the emulator itself...

**Comment by midwan** [comment]
Closing this, as we can't fix it from the emulator side.

**Comment by MichaIng** [comment]
@matenkoH @midwan 
Just fall over this, while searching for DietPi-specific issues with Amiberry. The issue should have been resolved with DietPi v6.23, where we added `dbus` + `libpam-systemd` install and unmask of `systemd-logind` service. This was to solve another issue: https://github.com/midwan/amiberry/issues/514

Background: For login sessions, `systemd-logind` is responsible to register those sessions with `pam_systemd`, which creates the XDG_* session variables. In server setups this is not required, hence we mask this service (if not chosen differently via dietpi.txt), which saves around 10 MiB RAM and reduces tasks and logs on every login/shell session/sudo call etc. Instead it is installed/unmasked automatically when installing any desktop, and since v6.23 as well when installing Amiberry.
