### ISSUE TITLE
Implement Save/restore state with controller button

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#454]
Save and restore states doesn´t working directly with controller buttons.

**Comment by HoraceAndTheSpider** [comment]
Yes, i'm aware of this. 

I will be looking at various save-state extras (more slots, auto-load with the auto-booter etc), but this one might be a bit tricky because of being in-emulation (while the current functions are in-menu) and there are still limits on the number in internally mapping joypad buttons we need to find a way around.

I will be looking at extra joypad options in the future though for this.

**Comment by Tomato1981** [comment]
What about quickly open menu save and exit? So people will see some flash of menu, but it could work.
And if you use a hot key + another key, the button limit might not matter.

Another nice thing would be the possibility of a key combination on one button. For example, in Golden Axe, you have to press Fire+Up to jump up.
