### ISSUE TITLE
Read Line mode from config

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#466]
Amiberry can save "Line mode" (Single, Double, Scanlines), but it can not read from "uae" configuration file.
In the file is written double or double2, but after start Amiberry is Linemode Single.

Thanx a lot.)

**Comment by c0d3h4x0r** [comment]
+1, I'm noticing the same thing.  "Line mode" does not get loaded and applied correctly from the configuration file.  This is a PITA b/c I have to switch it back to "Double" manually every time I launch Amiberry in order to avoid migraine-inducing flicker from the interlaced mode I use for Workbench.

**Comment by mrfomt** [comment]
I run the latest Amiberry 2.25, and the scanlined option doesnt save when using .uae file for a game

**Comment by midwan** [comment]
This seems to work normally in `dev` at least.
The config file saves and updates the option
```
gfx_linemode=normal
```
to the value:
```
gfx_linemode=scanlines
```
as expected
