### ISSUE TITLE
Amiberry Android APK

### ISSUE THREAD

**Issue by 03stevensmi** [midwan/amiberry#470]
It has been a long time since we herd news on amiberry for android!
Last we got told was its coming soon and a paypal fundraiser (witch looks complete).
That was at new year at the beginning, its now nearly summer and am really missing using 
my amiga on shield tv since oreo. 

It has been nearly a year without a fix or usage for android 8 TV and i gave up hope
for a fix for UAE4ARM. :(

Is there any possible way for a beta apk fix, release or even news on amiberry for android?
Cheers!

**Comment by midwan** [comment]
@03stevensmi 
I don't believe I ever mentioned "coming soon" from my side, although it is coming.
The fundraiser was for purchasing the tools that would help the process, which is indeed done and work has begun.

I managed to get the SDL2 components building correctly, which was one of the show-stoppers earlier. But there is still work to be done (the rest of the dependencies need to be added, and finally Amiberry itself). Progress is slow due to the limited available time, but it is happening.

Meanwhile, we have another 2 related issues (#241 and #206), so it seems like this one is a duplicate, so I'll be closing it. Let's keep the discussion on the related issues instead.
