### ISSUE TITLE
Scanlines in Pinball Dreams and Pinball Fantasies

### ISSUE THREAD

**Issue by mrfomt** [midwan/amiberry#471]
Pinball dreams looks better in 640x270 with v. offset -5. Scanlines doesnt looks good. Same with Pinball fantasies, should have height 270.
Amiberry ignores my whd files placed in/opt/retroarena/emulators/amiberry/whdboot/game-data where the  whdload_db.xml, but Amiberry doesnt seem to read it.

**Comment by midwan** [comment]
@mrfomt 
I believe `.whd` files are considered deprecated now, but we could modify the settings for specific games in the XML file instead.

@HoraceAndTheSpider could you please confirm when you get a chance?

**Comment by DBMandrake** [comment]
For what it's worth I've found most games including SuperFrog need offset -5 and vertical resolution of 262 to avoid cropping either the top or bottom off the image.

For some demos it's beneficial to use a width of 704 as well since the Amiga supported overscan in excess of 640 pixels and while workbench didn't use it many games and most demos did.

So my default config is 704x262 with a -5 offset, which seems to work well with everything I've tried.

**Comment by midwan** [comment]
Closing this - `.whd` files are obsolete and shouldn't be used anymore.
Instead, we have two approaches:
1) Use `.uae` config files per game
2) Use WHDload `.lha` archives and the `whdload_db.xml` will automatically detect the settings for you (and you can contribute with improvements there if necessary).
