### ISSUE TITLE
Speedball 2 momentarily pauses using retroarch keyboard as joystick 

### ISSUE THREAD

**Issue by JTilla** [midwan/amiberry#474]
I have a joystick plumbed into to a HAT into the gpio pins on a pi.  I mapped the stick in Emulation 
Station all working fine and have tested multiple games. When playing Speedball 2 however when I move a direction on the stick the game pauses momentarily.  I can use a gamepad fine.

**Comment by midwan** [comment]
@JTilla 
This is going to be hard to figure out, especially since I don't have similar hardware to test with.
Could you try opening an SSH session remotely, and running something like `htop` during this test? Try to see if there's any spikes in CPU usage when you're using the controller for example, that might explain this behavior?

**Comment by RiaanJacobs76** [comment]
I have the same issue (also using GPIO with keyboard emulation), the reason its doing this is because if you look at the Speedball 2 manual, any other key other than the assigned keys for the game will pause/unpause it. Not sure how to work around this in Retroarch though.
