### ISSUE TITLE
Amiberry/WHDLOAD won't load when wireless controller is turned on (retroarch.conf)

### ISSUE THREAD

**Issue by mth75** [midwan/amiberry#481]
Hi all,

I succeeded in compiling SDL2 and the Amiberry SDL2 version on my RPI3b+/Retropie setup. I can start the Amiberry SDL2 executable and even run a whdload game (from the config menu). Running games (whdload games/lha) from my Amiga/Emulationstation menu won't work however. The screens turns black for a few second, I can see a mouse pointer for a second and then ES throws me back to the Amiga game menu. I tried everything I can think of.

So the question is, after compiling SDL2 and Amiberry SDL2, what steps are needed for an RPI/ES setup?

Cheers!

**Comment by midwan** [comment]
RetroPie comes with SDL2 pre-installed, but it uses the `rpi` back-end. When SDL2 is compiled to use that back-end, it makes use of Dispmanx behind the scenes. This creates a problem for the "Dispmanx" versions of Amiberry, because you cannot have two applications opening exclusive access to that back-end simultaneously.

For RetroPie, I think your best solution if you want to run the SDL2 version would be to use the non-dispmanx binary of Amiberry (e.g. amiberry-sdl2). That will use whatever back-end SDL2 provides in the system, so it works under RetroPie as well. 

The performance might not be as good (but please test and let us know) but it will work. And it also means you don't have to compile SDL2 yourself.

**Comment by mth75** [comment]
Thx for your answer. But, i'm already using that version. When I start the Amiberry it works. When I start a game (whdload), it doesn't work. So, I swapped the "Standard" Sdl1 amiberry version for the Sdl2 amiberry version. I suspect some config problems, I checked it all however.

**Comment by midwan** [comment]
The Amiberry GUI uses standard SDL2 (so it will show using whatever back-end SDL2 is configured with), but the game screen will depend on the version:
- The Dispmanx version will open a Dispmanx screen directly
- The SDL2 version will also use the same method as the GUI, using whatever back-end is available/configured.

If you're seeing a black screen after the GUI, I strongly suspect that you're running the dispmanx version of the emulator.

**Comment by mth75** [comment]
But, i am able to run a whdload package (game) from the GUI itself

**Comment by midwan** [comment]
OK, so if you just use a quickstart option from the GUI and hit start, do you see the kickstart screen?
If yes, then there's no problem showing the emulation screen in general, and your problem is more specific to the game/configuration you have.

**Comment by mth75** [comment]
yes it does show the KS screen indeed.

**Comment by mth75** [comment]
Is there a way to trigger a verbose logging?

**Comment by midwan** [comment]
Yes, check the FAQ: https://github.com/midwan/amiberry/wiki/FAQ

What are you trying to run exactly? Can you provide specific steps, including filenames, to see if we can recreate this?

**Comment by mth75** [comment]
Thx, yes I can. I'll follow up.

**Comment by mth75** [comment]
[amiberry_log.txt](https://github.com/midwan/amiberry/files/3203836/amiberry_log.txt)

**Comment by mth75** [comment]
All Whdload packages which work under Amiberry SDL1

**Comment by mth75** [comment]
I did some more troubleshooting, the problem is quit simple it seems. WHDLOAD games won't boot with the default (uaeconfig (AutoBoot Configuration [whdload])). I've added the configs.
[Archive.zip](https://github.com/midwan/amiberry/files/3204456/Archive.zip)

**Comment by HoraceAndTheSpider** [comment]
The problem may be that you have this default uae Config at all.

Some of those files look quite out of date, some maybe something there clashes on SDL2 version.

 when using the WHDLoad booter you should really have no Config at all to test from if you have issues (let Amiberry create a default) .... the WHDLoad booter doesn’t actually use the Config files until you save a game specific one. It uses the QuickStart options and minor adjustments from the XMl file only by default.

**Comment by mth75** [comment]
I tried your (good suggestion), same result sadly.

**Comment by mth75** [comment]
Let me handle the problem in other way. 
Say I want to "upgrade" my RetroPie Amiberry SDL1 install (installed with the package manager, binary or source compile). 
Say the next step is compiling SDL2, conform the instructions and for the right backend (which I did). 

And at last I compile the Amiberry SDL2 version, which leaves me with a binary. 

The question would be ... what is the next step. I copied the binary to Amiberry folder and made a new symlink. Is there anything additional I have to do, configuration wise?

**Comment by mth75** [comment]
Forget all of the above. I noticed that when the wireless controller is off, all games work (whdload packages), when I turn it on, I have (this thread started with this):

> the screens turns black for a few second, I can see a mouse pointer for a second and then ES throws me back to the Amiga game menu. I tried everything I can think of.

This is strange a strange problem. The controller settings are of course from the retroarch.conf.

**Comment by HoraceAndTheSpider** [comment]
Can you switch on the logfile and pastebin the output for both with and without the controller please

**Comment by HoraceAndTheSpider** [comment]
Also a copy of the retroarch configuration file for the spacific controller ... e.g. `my controller 123.cfg`

**Comment by mth75** [comment]
I will send you the logs. In the meantime, it turns out that my PS4 dual shock controller is responsible. Everything works when I use my 8bitdo gamepad controller. How about that

**Comment by midwan** [comment]
This has been updated with the new `dev` version:
- There is now a pure Dispmanx version that is the default per RPI platform, which should work "out-of-the-box" with RetroPie as well. 
- The old SDL1 version is deprecated and no longer supported with the next release, so everything is SDL2 which provides the improvements in gamepad handling among other things.
- There was a bug in Amiberry's reading of the controller config, which resulted in some DPads not working at all while the other buttons did. If you had such a problem, try updating with the latest version (either `master` or `dev`).

If you're still getting problems after updating to the latest `dev`, please let me know with an up-to-date description of what the problems are, so we can take a look. Otherwise, I believe we can close this issue.
