### ISSUE TITLE
Weird mouse issue

### ISSUE THREAD

**Issue by RaoulAngel** [midwan/amiberry#494]
So, I set up the dietPi distro of the easy install file, but when it gets to the config screen (the F12 screen) the mouse is a large graphics arrow that does not line up with any of the choices.  For instance I have to hover 3 menu items down to click on the top item.  I had to resort to using the keyboard keys (tab, arrows, enter, etc) but it just isn't working out.  How do I fix this?  Thanks

**Comment by midwan** [comment]
I believe this is a bug in some version(s) of SDL2.
Perhaps it's better to remove the custom cursor altogether, or at least give the option to disable it, so we can avoid this issue.

I can do that after I get back home, around the end of next week.

**Comment by midwan** [comment]
SDL2 v2.0.10 at least doesn't have this bug, from what I can see.
Tested on Raspbian Buster Desktop, on an RPI4. It should be the same on DietPi as well, since this is an SDL2 bug.

You could try installing the latest SDL2 release, either from their "Release" archives (https://libsdl.org/download-2.0.php) or the cutting edge version from their Mercurial repository directly: https://libsdl.org/hg.php
