### ISSUE TITLE
Grey shades of color in some text in GUI

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#496]
**Describe the bug**
With the rpi4 (at least) the colors in the GUI seems a bit off. Some of the text is very light grey, so it's hard to see the text. (Debian Buster). 

**To Reproduce**
Compile and start amiberry on buster. I compiled SDL2 as per instructions.

**Expected behavior**
Readable text :-)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian buster

**Smartphone (please complete the following information):**
 - Device: Raspberry Pi 4GB

If you compile the rpi3-sdl2 target (not dispmanx) the text is gone on almost everything. Also, the buttons don't react to mouse clicks (but the menu items on the left do)

**Comment by 5schatten** [comment]
*Weird :smiley:

This is not a RPi exclusiv bug since my Rockchip & Amlogic builds have the same issue as described above. All of my builds use the *-sd2 target so I guess it's somewhat linked to "recent" SDL2 changes.

**Comment by midwan** [comment]
I'll be back home at the end of next week, and I'm already trying to get my hands on an RPI4 to test this. It currently seems to be out of stock, but as soon as I secure one I'll look into it.

**Comment by midwan** [comment]
I can recreate this on both the RPI4 and RPI3 when running Buster.
Since Buster includes SDL2 2.0.9, and I only tested with the bundled SDL2, I suspect that there might be something there.

Did anyone test with the latest SDL2 from Mercurial to see if the issue persists?

**Comment by solskogen** [comment]
I tried with both 2.0.10 and the latest from Mercurial. Problem is still there. 
I'm about to install Arch Linux on my rpi4 now to see if the problem is there as well.

**Comment by midwan** [comment]
@solskogen 
Thanks for confirming. I've updated the title to better describe the problem also.

**Comment by solskogen** [comment]
Same issue on Arch Linux ARM (with SDL-2.0.10)

**Comment by midwan** [comment]
I've got an interesting scenario: I updated Guisan with the latest changes, and recompiled. The new version still has the issue, but it shows in different text now. The bullet lists are grey, and some labels are a shade of grey so light it's almost impossible to make out.

I'll test it a bit more with Guisan samples, to see if I can find some more clues.

**Comment by midwan** [comment]
It seems that bit depth changes the effect somewhat.
If I switch the GUI to 16-bit instead of 32-bit, some of the text that was light grey (same color as the background) is now a darker shade of grey, but not black as it should be.

I still don't know what causes this exactly, and I can't see anything suspicious in Amiberry's code. A good example is the Shutdown button, the code for it is identical to the other buttons next to it, but it shows the text with a grey shade instead of black.

So far I haven't been able to find anyone else facing the same issues in other applications either, so it's unclear if this is Amiberry-specific or not.

I also experimented with Guisan a bit. I've updated it to the latest version (which affected which text labels had incorrect color, but didn't fix the problem). The samples that come with it seem to work normally.

**Comment by 5schatten** [comment]
Well after your latest updates Amiberry fails to build for me:
https://pastebin.com/YY9dNHk4

**Comment by midwan** [comment]
@5schatten 
Hm, looks like you're missing the OpenGL headers in your system - we didn't get this error on Raspbian at least.

The issue is in the file `guisan-dev/include/guisan/opengl/openglimage.hpp` it seems, and specifically in this like:

```
#include <GL/gl.h>
```

which used to be:
```
#include <SDL_opengl.h>
```

I'll revert that line as it should work with the previous value as well.

**Comment by midwan** [comment]
Fixed with 93722aa062c472652d690c188b4eb3f29a8a3235 and merged into master with 0714511543facbdec5a9505cad7427f53edddd5f

**Comment by 5schatten** [comment]
Next error ;-) The thing is OpenGL headers are not present & not needed on OpenGL ES builds.
```
src/opengl/openglgraphics.cpp:71:10: fatal error: GL/gl.h: No such file or directory
   71 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
```

**Comment by midwan** [comment]
@5schatten 
Fixed that as well, it should work now.
