### ISSUE TITLE
Line mode: single not functioning correctly

### ISSUE THREAD

**Issue by emuchicken** [midwan/amiberry#497]
**Describe the bug**
Display/ Line mode single displays same as double

**To Reproduce**
1. Go to Display screen/
2. Set resolution to 320x200
3. Select Line mode Single

**Expected behavior**
A clear 320x200 resolution.

- When selecting to linemode- double, the same screen is displayed

- Retropie 4.5 / pi 3b+

**Comment by midwan** [comment]
@emuchicken 
I think you might be confusing what this does:
- Double line mode will eliminate the flicker of Interlace resolutions, but doubling each line.
- Single line mode is the default, and will show the lines as they are originally (i.e. with flicker on Interlace modes).

You won't be able to see a difference in a non-Interlace resolution, such as 320x200. Try something like 640x512 however, and you'll see that with Double line mode the interlace flicker is gone.
Bear in mind that since this effectively draws double the amount of lines on screen, it comes with a performance cost.

**Comment by emuchicken** [comment]
I was actually attempting to get as much performance as possible, for games such as "Jim Power"- and could get great gains when lowering to the lowest res.  Noting that the regular screen resolution for Amiga was 320×200, I tried to emulate the settings, and found that the "single" linemode  would effectively "double" and give a vertically stretched image, rather than what should be shown.   I also noticed a sizable improvement in performance.  Does this make any sense?

**Comment by midwan** [comment]
@emuchicken 
The image is always somewhat stretched to fill the image, regardless of the resolution used. The Correct Aspect ratio can be kept with the relevant option enabled (leaving black areas where necessary), otherwise the image will be distorted to fill the screen fully.

The difference the resolution option makes is the area the emulator will be drawing into internally. Obviously lower resolutions will give some performance advantage, but whatever you choose will be scaled accordingly to fit the same screen space on your monitor (and native resolution you're running on!). So if you're after maximizing performance, you might want to experiment with lowering the host resolution also (i.e. try not running 1080p if you're only going to run low resolution games).

The Single and Double line modes are not what you think they are:
- Double mode is meant to eliminate the flickering effect in Laced modes. That's it, no difference should be visible in the screen size visible on the monitor. To do this, it draws double the amount of lines internally (which is why it comes with a performance cost) and the result is shown scaled as usual.
- Single line mode is the normal drawing mode, where each line is drawn exactly as it would on a normal Amiga.
- Scanlines line mode, uses a similar trick (drawing double the amount of lines, so again it comes with a performance cost) to emulate the "scanlines effect" that CRT monitors have. It's just a visual preference, again no change in the size of the displayed area.

I hope that clears things up a bit more, let me know if you have any more questions.

Considering the above, I think this issue should be closed as in fact, the Line mode option does work as expected. :)
