### ISSUE TITLE
Cannot save custom controls

### ISSUE THREAD

**Issue by Goffer-dk** [midwan/amiberry#498]
I have unfortunately turned my controllers sidways when i assembled the arcade cabinet, that issue was easily leviated by editing the configs for the different emulators and works fine, but i cannot get Amiberry (latest version) to save the config, i can update it while in-game and that works, but when i reset they have changed back to default.
I've used my limited linux skills to look in the CFG file, and that looks like the keymapping are correctly changed.
Any suggestions on that?

**Comment by midwan** [comment]
You will need to save the changes to a config file (`.uae` file) for them to stick, otherwise they will only apply for the duration you're running the emulator.
You can save game specific settings with `.uae` configs (one per game), or you can have some generic settings that apply to all games with the `hostprefs.cfg` file.

@HoraceAndTheSpider might be able to give more details on this, in case I missed something. ;-)

**Comment by HoraceAndTheSpider** [comment]
Nothing new to add here - that is correct, the .uae Config will need savings for each game - there is no option to remap at a host level, although you could create a customised Retroarch controller Config for this?

**Comment by Goffer-dk** [comment]
Hi both,
Thanks for the input, just to understand @HoraceAndTheSpider correctly, i need to have a UAE file for each game for this to work?
is all this done from within the emulator? I tried searching for some articles without luck

**Comment by midwan** [comment]
@Goffer-dk 
You can create `.uae` files from within the emulator's GUI, or you could also edit them manually if you wanted (they are text files after all). But I'd recommend you use the GUI to make sure you don't mess anything up. :)

The alternative as @HoraceAndTheSpider suggested, is to create a standard `Retroarch` config, which is what RetroPie uses also. That will be applied automatically if found by the emulator, for all games (unless of course, they have an overriding `.uae` file!).
