### ISSUE TITLE
[Jim Power] slow no matter what

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#532]
JimPower_v2.1_0068

Apologize to open another ticket for that game but I just love it and to be not able to play it on a Pi3b+ makes me sad :) I had some hope with the new Amiberry release yet I understand there might be better chance with a Pi4. Feel free to close that issue off anytime if there's nothing else that could be done.

**Describe the bug**
Game still runs slower than expected right from the intro screen but also during gameplay. This time it's not only during the intro screen as previously mentioned in #58.

**To Reproduce**

1. Launch the game
2. Music seems to play normal speed during the Loriciel logo.
3. As soon main menu screen does appear the slowdown is immediate. 
4. Slowdown even during normal gameplay.

**Expected behavior**
Game to run full speed.

**Desktop (please complete the following information):**

- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0 the one shipped with Retropie. 

**Additional context**
Given some other games run full speed only when Fast Copper is turned on (Agony, Fire & Ice, Brian the Lion) I gave it a try too for Jim Power but without success. Also increasing CPU clock speed does nothing.

**Comment by midwan** [comment]
This one's a tricky one...
On the RPI4, it's playable at 50 FPS using the Dispmanx version, with 89% CPU usage.
CPU usage drops a bit to 77% if you enable Fast Copper.

The RPI3 doesn't have a fast enough CPU to keep up with this, unless we enable Frameskip.
The main issue is that some routines are hit heavily in a loop, and they have to run on the same CPU core - so we're limited by the maximum speed of the core, in this case. 

Raising the emulated CPU speed will only make things worse, not better (since the emulator will have to speed more cycles to emulate a faster CPU, hence less are available for the chipset emulation which is needed for this game). You can see that easily if you use an A1200 config instead of an A500 one, it will run slower for this game.

I'm not sure what else we can do about this one, besides generic optimizations which we are already implementing everywhere we can. However, some times we have to remove optimizations that were proven to be buggy - it's better to be a little slower and work properly, instead of not working at all and crashing.

**Comment by midwan** [comment]
I did some tests with inlining some functions, and managed to squeeze a few more FPS out of it (29 instead of 25, so still nowhere near the 50 it needs).
I'll test it a bit more and see, eventually I'll push these up in a new update unless I find any problems.

**Comment by midwan** [comment]
By tweaking some compiler options, I managed to take it up to 35 FPS with Fast Copper, on the RPI3.
For now, that's the best we can do I think. If we find a way to make it any faster, we will, of course.

**Comment by joolswills** [comment]
The removal of the fpic flag made a significant difference to performance thanks. Certainly position independent code has an overhead on arm. Btw rename-registers is enabled by Ofast - which I guess you know as you removed it.

-Ofast and -O3 could produce slower code in some cases than O2 on arm due to loop unrolling and small CPU cache. Might be worth testing O2 but enabling vectorization etc (may be negligible though).

Btw. 

`gcc -Q --help=optimisers -O2` (change O2 to whatever)

And

`gcc -Q --help=target` 

Is useful to see what is set by default etc.

**Comment by midwan** [comment]
@joolswills 
Thanks, I'll test with O2 as well and see what kind of difference we have.

**Comment by joolswills** [comment]
For vectorization you will need `-ftree-vectorize -funsafe-math-optimizations` also on arm.

**Comment by midwan** [comment]
@joolswills 
I tested with -O2 and `-ftree-vectorize -funsafe-math-optimizations`, but it didn't make any difference in the performance in this game (still only managed 30 FPS with Fast Copper on the RPI3)

**Comment by joolswills** [comment]
Might still be preferable though as compiling is quicker. I am going to override Ofast on RetroPie as I felt there were some minor improvements in some demos looking at the FPS (eg Arte) but it's difficult to accurately benchmark things like this.

**Comment by midwan** [comment]
@joolswills 
OK, I'll need to test on a few more scenarios as well (I only tested Jim Power for now) to get a better idea of any differences.

**Comment by joolswills** [comment]
Btw I'm testing on a rpi2. The difference is probably minor anyway so it's not really an issue.

**Comment by piotrorlowski** [comment]
I tested it with a real Amiga 500 upgraded with PiStorm and WHDLoad installed on an emulated hard drive.

Slow down appears on parallax menu screen also at some points in the game, got two versions of this game from the Web both versions seem to have the same slowdown.

I also tried real floppies and emulated GOTEK floppies for this game.

On WINUAE it runs smoothly both run by WHDLoad and in floppy drives.

Real Amiga 500: PiStorm is emulating a 68020 chip, I got a lot of memory as well both CHIP and Fast.

The question is if there's some fix to it, for example, some WHDLoad configuration that might fix that problem?

**Comment by midwan** [comment]
@piotrorlowski 
You didn't mention what platform you tested it on, nor which version of Amiberry.
You cannot compare things with WinUAE, as that runs on a much more powerful CPU - that being said, the game runs fine on a Pi4/Pi400 which also has a more powerful CPU than the Pi3.

**Comment by piotrorlowski** [comment]
@midwan I tested it on real Amiga 500 hardware (like real Amiga 500 computer) with PiStorm installed with HDD emulation and WHDLoad installed. Do you know what I mean by a real computer? ; )

**Comment by midwan** [comment]
@piotrorlowski 
Why are you mentioning this on a closed Amiberry Issue then? How is this related to Amiberry?

**Comment by piotrorlowski** [comment]
Well, it's the only thread about Jim Power game that I found on the Internet and I thought if it's the same issue, then I'll give it a try and ask a question if there's some option in WHDLoad to make this game run at 50FPS.
