### ISSUE TITLE
performance drop using amiberry 3.0 @ Retropie 4.5.2 on RPi1

### ISSUE THREAD

**Issue by MHB8080** [midwan/amiberry#535]
After/during the upgrade of the Retropie (to 4.5.2) the Amiberry 3.0 was installed, running on the overclocked Rasperry Pi 1, the emulated games performance dropped significantly.
With the Amiberry 2.xx the performance was not incredibly great, but it was fair enough for the majority of games I am interested in (e.g. IK+, Project X, and many others).

My question is whether the RPi1 is abandoned from now on (with Ameiberry 3.0+) or whether there is the chance to support the (old, I know....) RPi1, at least as it was in Amiberry 2.xx? I mean from the performance POV.

**Comment by midwan** [comment]
@MHB8080 
Please try with the updated v3.0.2, the performance should be somewhat better there.

**Comment by MHB8080** [comment]
@midwan 
Hi, I tried to compile the 3.0.2 from sources for the RPi1-sdl2 (I am not sure whether you meant this under "try v3.0.2"), but I managed to compile it. The produced amiberry executable shows the GUI, but after the game emulation starts there is only black screen, but the sound is there. I tried to compile and run the 3.0.0 built from sources too, with the same effect - the sound plays, but black screen) - I did probably something wrong, because the 3.0.0 which came with the update works (slowly, as described previosuly, but with working display). Please advice. Thanks a LOT!

**Comment by midwan** [comment]
@MHB8080 
The target platform you should test with is "rpi1", not "rpi1-sdl2". The first one uses Dispmanx for maximum performance, the second one uses pure SDL2 which depending on your environment, might need some extra configuration.

**Comment by MHB8080** [comment]
@midwan 
Hi Midwan, I have working amiberry after building it with "PLATFORM=rpi1" as you mentioned. I've built both 3.0.0 and the 3.0.2, but both are running slowly, or better - I am not able to see the difference in the game (IK+). I've built the 2.25 too from sources - et voila - there everything is working quickly (well, as quickly as it is possible on RPi1, in any case the old good IK+ is playable again). I will continue to use the 2.25 I've built now, but I fear the future :-D

P.S.: I've noticed the difference in the compiler settings between 2.25 and 3.0.2, just for fun I've built the 3.0.2 with the CFLAGS used in the 2.25, but without noticeable effect.

**Comment by joolswills** [comment]
To build 3.0.2 on retropie you don't need to do it manually. Just install from source for latest master branch code. Binaries are currently at 3.0.2 though - updated yesterday.

**Comment by midwan** [comment]
@MHB8080 
What kind of performance did you get from v2.25 that you don't get from v3.0.2?
I tested both versions on an RPI-ZeroW, with IK+ and I don't see any significant difference in performance.

In both cases the game runs too slow (around 20 FPS in the title screen with v2.25), even with Frameskip enabled.

**Comment by MHB8080** [comment]
@midwan 
Hi Midwan, OK, I tried it right now again. And it is true the status line says in both cases that there are about 25 FPS, but I cannot help myself - the IK+ running on 3.0.x is simply slow motion compared to the 2.25.
I can make some short videos if you think it is a good idea.

**Comment by midwan** [comment]
I run the game on both 2.25 and 3.0.3, on the same RPI ZeroW here, so there's no need for a video I think :)

I saw a small speed difference (maybe 3 FPS? it wasn't stable so I'm not sure) but beyond that, the game was too slow in both versions. The small FPS difference might be due to the overhead of multi-threading when running on a single core, which the Zero/RPI1 have, as that's something that was fixed/improved from the v2.25 release - something that improved the performance on all multi-core platforms.

I'm not sure we can do anything about this in any case, the platform is just not powerful enough for most cases. We have scenarios where even the RPI3 is stretched to its limits and struggles to keep going at 50 FPS, so you get an idea of the kind of demand we have on the platform.

**Comment by MHB8080** [comment]
@midwan 
Hi Midwan, me again. Apparently I am the only person on the planet having this problem, thus, here is my last post regarding this topic with the last experiment.
I wanted to measure the performance somehow "objectively" and I've used the AIBB 6.1 to do it, and I've created the module containing all the tests under amiberry 2.25. I was REALLY SURPISED after doing some few tests with amiberry 3.0.2 where AIBB didn't noticed any difference in performance. In any case I measured the LineTest duration using stopwatches, and under 3.0.2 the test took 18 seconds with frameskip and some 23 second without frameskip. Under 2.25 the same test needed just some 12 seconds with frameskip (all tested using the same amiberry configuration file - the A1200 conf with frameskip as descibed above and with scaling method set to "nearest" for 3.0.2).
OK, in any case -> thank you for your answers and effort.

**Comment by midwan** [comment]
@MHB8080 
Are you running on a monitor at 50Hz?
If so, I just fixed a bug which might have been affecting what you saw - the dispmanx versions had a problem in the vsync calculations, which only showed when running on a monitor with the same refresh rate as the one emulated (e.g. 50Hz for PAL, 60Hz for NTSC).
The symptom was that you got half the expected framerate = 25 FPS for PAL instead of 50.

Try upgrading to 3.0.4 and see if this helps in your case as well?
