### ISSUE TITLE
[Amiberry 3.0.2] Add Auto-Center options in GUI

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#538]
**Describe the bug**
Not sure the screen auto-center does work properly. For the screen height at least. In the few games tested the width was ok.

**To Reproduce**
I'm using a specific set of games I know works great that I remember enough to be able to judge performance, etc.

1. Let's stick to Blues Brothers from Titus for the time being. Like for most games from this dev/editor it was fine to set `SCREEN_HEIGHT=200` to get it almost fullscreen with no cropping/black borders.
2. Open Amiberry GUI. Go to Display / Screen Setup and set height to `200`.
3. You could then see cropping at the bottom and black border to the top. (Cropping might not be appropriate I just don't know how to call that!)
4. You have to increase that value to `240` or so to get the entire sceen yet with black borders.
5. NOTE: since 3.0.2 the screen/hud now "folds/unfolds" properly at the beginning of each stage (right after the map).

**Expected behavior**
To be able to get a wider screen as it was the case with 3.0.

**Desktop (please complete the following information):**

- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0.2 compiled from source.

**Additional context**
This release definitely improves situation in few games re performance (Jim Power, Agony, Brian Lion, etc). No need to set `FORCE_COPPER` any longer. Just that potential screen issue not present on 3.0. 

FYI I've submitted a lot of [changes](https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/issues) to @HoraceAndTheSpider and the XML file but now with 3.0.2 the values are no longer valid.

**Comment by joolswills** [comment]
The screen position on sensible soccer doesn't look right but I will bisect and give more info.

**Comment by midwan** [comment]
I will add the Auto Center options (Horizontally and Vertically) in the GUI, so the users can control if they want it enabled or not.
The options can of course be saved in the config files as well.

**Comment by joolswills** [comment]
Whilst looking into another issue I noticed that old configs missing the `gfx_center_horizontal/vertical` will default them to `none` rather than smart (which is the setting when making a new config).

Eg on sensible soccer if I resave the config these get set to `none`. I wondered if this could be a cause of centering issues for me/other users, but I need to test further to verify.

**Comment by midwan** [comment]
@joolswills 
The auto-center option was added and made the default in v3.0, but I took that away in the subsequent updates because we found a glitch in some cases (e.g. Banshee). The default is now the same as in WinUAE (none).

The option didn't exist in previous versions, so it's expected to be missing from the config files. ;)
