### ISSUE TITLE
Autoboot does not load .uae file on startup

### ISSUE THREAD

**Issue by tukicat** [midwan/amiberry#557]
I have only been able to reproduce this on Lotus 2, I am using the whdload version - Lotus2_v1.9_0497.

If I load this game using the WHDload autoboot I can then create .uae config using the configuration tab in the GUI. 

If I then exit out of the GUI and game and re-load it I believe that this .uae file should then load automatically, but it doesn't. I have verified that it has created the .uae file by using WinSCP and cheking the contents of the file. I can also load this .uae manually when in the Amiberry GUI.

I have attached a copy of the .uae file (I chaned the file extension to .txt as it won't let me upload .uae files). On this .uae I have added a custom command that maps the north button to joy2 up.

[Lotus2_v1.9_0497.txt](https://github.com/midwan/amiberry/files/3965503/Lotus2_v1.9_0497.txt)

**Comment by midwan** [comment]
@tukicat 
Where is your `.uae` file placed?
I believe it should be under `whdboot/` directory, and it should have the same filename as your started game `.lha` or CD image.

**Comment by tukicat** [comment]
@midwan 

Hi, 

My .uae files are placed in = /opt/retropie/configs/amiga/amiberry/conf.

The nameof the .lha is Lotus2_v1.9_0497 so it is the same as the .uae file.

I have also tried deleting the autoboot file and the .uae and starting from the beginning but the issue is still there. 

As I say I can only reproduce this on Lotus 2. Can anybody verify that the same thing happens for them with Lotus 2?

**Comment by midwan** [comment]
@tukicat 
I can try to recreate the problem here to see if it happens for me also.
Have you checked the file for permissions and ownership? Is it the same as other files there (just in case)?

Have you had other `uae` files work, with the same changes made in this one? It could be a case of the file actually being loaded, but some option(s) not being parsed correctly?

**Comment by tukicat** [comment]
@midwan 

Hi, 

Sorry I haven't replied on this, I wanted to so some more testing. 

I tried the same thing on the WHDload version of Agony, and it worked fine, the .uae automatically loaded. 

I thought it might be permission related so I reset the permissions using: -

sudo chown -R pi:pi /home/pi

However, the issue is still there. 

I then tried deleting all the autoboot files and any .uae, uninstalling and reinstalling Amiberry and starting from fresh. However, this still doesn;t solve the problem, and after a reinstall I still could not get the .uae to autoload when I start Lotus2_v1.9_0497.

I can load the .uae file from within the Amiberry GUI, so the .uae file is being created - it is just not be autoloaded. 

I think the issue is related to permissions, what permissions need to be set to the conf folder where the .uae are saved?

Have you managed to recreate the issue?

**Comment by amyren1966** [comment]
I dont know if this is relevant, but on Amibian 1.5ee I had problems getting the autostart to work.
I used the default paths, and the instructions said that in order to autostart, the configuration just had to be saved with the name autostart.
By default all the configs was set to be saved to /home/amibian/Amiga/conf
But it turned out that Amiberry was configured to locate the autostart file in /home/amibian/Amiga/Emulators/amiberry/conf
After changing the path settings in the GUI to match that, then autostart works.

**Comment by midwan** [comment]
@amyren1966 Amiberry should look for configs in the configured path, as found in the Paths panel.

**Comment by midwan** [comment]
@tukicat 
I tested it with the latest client version (it's currently Lotus2_v1.11_0497), but I can't recreate the problem.

Here's the simple test I made, in case it helps:
- Loaded the game using the command-line options: `./amiberry -G -autoload=/home/pi/projects/amiberry/lha/Lotus2_v1.11_0497.lha`
- Opened the GUI, changed the Display settings (set Height to maximum) and enabled Show Status Line in the Misc panel. Just something that would make it obvious that the config file got loaded.
- Saved the config by going in the Config panel and clicking Save.
- Exited the emulator.
- Re-run the same command-line
- Notice that the saved options were automatically loaded with the config.

**Comment by amyren1966** [comment]
@midwan In Amibian Amiberry is launched from a command line menu, by typing the number of the script Amibian should run. 
This particular script Amibian uses to start Amiberry does start Amiberry with a commandline pointing to a specific uae file:
`./amiberry -f /home/amibian/Amiga/Emulators/amiberry/conf/autostart.uae`
But Amiberry itself was set to the configs path /home/amibian/Amiga/conf

Because of this it did not help saving any config as autostart.uae in the pre-set path.
Clearly in my case it was a Amibian setup issue, but I mentioned it just in case the retropie distro had the same mixup.

**Comment by midwan** [comment]
@amyren1966 
Yes, but the path you're referring to, is not hard-coded in Amiberry itself. It comes from the default configuration which is in `conf/amiberry.conf` - So in other words, the default configuration in Amibian had an incorrect path, set for config files. ;)

**Comment by amyren1966** [comment]
@midwan Yes, that was also what I tried to imply in my post:)

**Comment by midwan** [comment]
Closing this, since I don't see anything I can do from my side.
