### ISSUE TITLE
Userland dispmanx compile issues

### ISSUE THREAD

**Issue by br6** [midwan/amiberry#567]
I am using the latest manajaro arm 64bit build for my pi4 4gb.
I have run cmake for the userland, setup the instructions and added user to video,
when I compile and run amiberry I cannot see the window for amiberry.

How can I figure out if something was wrong in the cmake for userland or amiberry?

I am logging in via vnc to see the desktop and manjaro arm is installed via pinn so I have a boot and root partitions (boot contains fw etc)

**Comment by midwan** [comment]
@br6 
There are a few things you mention here that I find confusing:
* Dispmanx doesn't work in 64-bit, but you mention it in your title
* You mention the userland, so I'm going to assume you're trying to get the rpi 32-bit userland working there, in order to use Dispmanx?
* Which target of Amiberry did you compile to test with?

Just to be clear, you could have avoided all this if you used the 64-bit RPI target in the Makefile, which was designed to work with Manjaro in the first place. Of course, you wouldn't have Dispmanx there, but pure SDL2 - which you'd have to configure to have KMSDRM support if you wanted it to run from the console without X11.
We have a dedicated wiki article for this as well: https://github.com/midwan/amiberry/wiki/Compile-for-Raspberry-Pi-64bit

**Comment by br6** [comment]
I followed this part on the link 
DispmanX

You could also use this very unsupported way of speeding up the emulation by using DispmanX, but it requires some fiddeling.

git clone https://github.com/raspberrypi/userland.git
cd userland 
./buildme --aarch64 
Compile amiberry like so: 
make PLATFORM=pi64-dispmanx

Create the file /etc/udev/rules.d/10-vchiq-permissions.rules and insert: SUBSYSTEM=="vchiq",GROUP="video",MODE="0660" Add yourself into the video group if your not already there: usermod -a -G video [your_username] Reboot, then you are ready to start amiberry.

I assumed userland was updated with support now for rpi4 aarch64 (my knowledge is limited Other than mmal and maybe other goodies for 3d accel for pi64bit)  so I ran this in Manjaro from the amiberry-dev git

**Comment by midwan** [comment]
@br6 
Which Amiberry target did you use then? Because the Pi-64-bit does not use Dispmanx, even if you have it installed with the method above.
You'd have to modify the Makefile to use it and add `${DISPMANX_FLAGS}`, assuming the include paths referenced there are still correct in your environment (they are from Raspbian Buster).

**Comment by midwan** [comment]
@br6 
Sorry, I forgot we had a pi64-dispmanx target there as well, apparently :)

**Comment by br6** [comment]
Is the build instructions for userland not compliant for arch/manjaro?

Will amiberry work work on gentoopi64 ? Sakaki has been very active on userland and kernel updates . gentoo support would be great https://github.com/sakaki-/gentoo-on-rpi-64bit

**Comment by solskogen** [comment]
The instructions worked last time I tried (I wrote them), but is there a
specific reason why you can't use the normal pi64 build?

**Comment by br6** [comment]
> The instructions worked last time I tried (I wrote them), but is there a specific reason why you can't use the normal pi64 build?
> […](#)

When you say normal you mean non dispmanx ? That has always worked. I thought I would try the dispmanx build to see any benefits in Manjaro.

**Comment by solskogen** [comment]
I've tried the instructions now, and it just works. But it will probably not work very well with VNC.
