### ISSUE TITLE
Pixel perfect scaling for PAL/NTSC modes in FullHD

### ISSUE THREAD

**Issue by boras-pl** [midwan/amiberry#571]
Most LCD displays connected to Raspberry Pi are FullHD (1920x1080)
1080 is a multiple of 270. Unfortunately such height value is not available in the 'Display' menu. As a workaround I must set manually gfx_height in a .uae config file and be careful not to touch the setting in the menu any more.
For pixel perfect scaling I currently use following settings:
```
;
; *** Display / Screen Setup
;
gfx_framerate=1
gfx_width=720
gfx_height=270
gfx_top_windowed=0
gfx_left_windowed=0
gfx_refreshrate=50
gfx_refreshrate_rtg=50
gfx_lores=false
gfx_resolution=hires
gfx_lores_mode=normal
gfx_linemode=double
gfx_fullscreen_amiga=true
gfx_fullscreen_picasso=true
gfx_center_horizontal=smart
gfx_center_vertical=smart
ntsc=false
```
Thanx this I have perfect pixels in my Workbench 640x512 PAL with some border.
I suspect that adding more values for gfx_width and gfx_height to be available in the 'Display' menu won't fix the problem in every case (e.g. other display resolutions, ntsc, etc.). I've found some magic in the code that automatically scales for Picasso modes. Is it possible to enhance it for PAL/NTSC modes as well?

**Comment by midwan** [comment]
Fixed with the commit indicated above:
- 270 is now a valid Height option in the presets of the GUI
- If a config includes values that don't exist in the available presets, it would have been used anyway but that wasn't visible in the GUI. It's now visible as a value there as well (but if you move the slider it will reset to using one of the presets).
