### ISSUE TITLE
Sound crackles with speeds faster than 25Mhz

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#592]
Hello i use amiberry 3.0.12 on a Raspberry Pi 4. RetroPie 4.5.13 is installed on Raspbian Buster.
I use AmigaOS 3.1.4.1 with Kickrom 3.1.4.

Every time i start a game or a whdload demo like Nexus7AGA i get sound crackles if i set the speed higher than 25 Mhz. I tried it with JIT and without JIT, too.

Because the JIT problem is solved since amiberry version 3.0.12 (BIG THANK YOU to PandTomB and midwan!!!) i REALY want to use it... and got very frustated about this soundissue.

Kind Regards
Retro1968

**Comment by Retro1968** [comment]
Here is my configuration file.
[++AmigaOS 3.1.4.zip](https://github.com/midwan/amiberry/files/4231306/%2B%2BAmigaOS.3.1.4.zip)

**Comment by midwan** [comment]
Faster speeds might have such an effect, since the CPU is running as fast as possible.
However, since you're trying to launch WHDLoad games and you are on RetroPie, why not use the WHDLoad Booter feature of Amiberry instead?

It was designed for this purpose especially, and in an environment like RetroPie it makes things much easier - each game runs with the best known compatibility settings directly. And you can scrape them so they show in RetroPie with all their screenshots, cover art, descriptions etc.

**Comment by Retro1968** [comment]
The sense of JIT is that the CPU runs as fast as possible. But the question is how to modify the Soundcalculations to end crackling. Maybe the solution is to calculate the sound more acurate.
Is this maybe a task where you need external help, e.g. from PandTomB?

Amiberry would win a lot prestige if that problem would get solved. :-)

**Comment by midwan** [comment]
This is not really an issue, it's by design:
- If you set the CPU speed to Fastest possible (or even worse, Turbo), the emulator will increase the number of cycles it allocates for CPU emulation to the maximum.
- Since it has to come from somewhere, that speed comes from reducing the number of cycles it spends emulating the custom chipset. With Fastest possible, it tries to keep a balance. With Turbo, it explicitly gives even more CPU time (useful for CPU-intensive desktop apps that don't use the custom chipset).

This behavior is not designed for games of course, so it might work fine with some, but might have unexpected behavior in others (like sound breaking up). It really depends on how each game or demo works.

That's why we have a CPU speed setting in the first place, and that's why we have WHDLoad slaves that "Fix" timing problems with faster processors (e.g. on real Amigas).
