### ISSUE TITLE
Tooltip for dropdown boxes in config

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#601]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When selecting a file from a dropdown box inside the emulator's config menu, it is difficult to determine which file is which if the path is longer than the visible portion of the dropdown box.  It would be nice to hover over the path name and a tooltip with the full path shown (with smaller font) pops up to aid in selecting the correct file.  Otherwise, the dropdown box is not helpful when filled with files having long path names.

**Describe alternatives you've considered**
Only other option is to use the '...' file selector, which defeats the purpose of the dropdown box.

**Comment by midwan** [comment]
@digitalMedic 
Adding tooltypes on Guisan is going to be a lot of work, since it's a very basic toolkit.
However, we could solve this in another way: show the filename first in the relevant dropdowns, and the full path afterwards (so if it's cut-off to the right, it doesn't matter much).

For example, like this:
`Workbench3.1.adf {/home/pi/amiberry/adf/Workbench3.1.adf}`

Or perhaps the full path is not needed, so it can be done like this:
`Workbench3.1.adf`

The config files will keep having the full paths, of course.
