### ISSUE TITLE
GUI not correct when launching CD32 file through command line

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#633]
So following your advice, I managed to launch CD32 images in iso or cue through the following command line :
`/usr/bin/amiberry -G -model=CD32 -cdimage=/userdata/roms/amigacd32/Kang Fu (1996)(ALTER interservice - Greed)[!][Amiga-CD32].cue -s ujoyport1_friendlyname=Sony PLAYSTATION(R)3 Controller -s joyport2= -s gfx_center_vertical=smart`

The game launches fine (at least the menus of the games, in several of them I had crashes when entering first level and even Out of Memory error appearing on the screen), the controller seems to be well configured (not 100% sure) however I see the following problems in the GUI :
- In Quikstart, instead of seeing thhe CD32 model selected I see Amiga 500 and 1.3 ROM for Config
- In Hard Drives/CD, Cd Drive is checked, however the name iof the ISO/CUE doesn't appear as selected in the combo box and actually the combo box is empty, there is no choice in it
- In Inputs, in Port0 I have mouse selected and in Port1 my controller appear, however its type is Default (which might be ok I don't know)

Others infos in the GUI seem okay :
- In CPU and FPUs there is a 68020 CPU with 14Mhz frequency
- In Chipset I have AGA with CD32 in extra
- In Rom is this okay, I have CD32 BIOS and CD32 extended BIOS appearing

**Comment by midwan** [comment]
@Voljega 
When you use the command line options, Amiberry uses them in a virtual config file in memory, then using that to launch the emulator. The Quickstart options are not part of the config file, they are there just as a helper function to quickly set the rest of the options according to the model selected.

Since they are not part of the config file, they are not saved and therefore not shown to be updated to what you used from the command line. So that part is normal. :)

The CD image selected however should show, as that is part of the config you're using.
The Input options have a separate choice for the type of controller, it will not be set to CD32 automatically. You can specify that in the command line as well, however.

Check the joyport.mode option when you save a config file to disk, and set it to CD32. ;-)

**Comment by midwan** [comment]
@Voljega 
It looks like the `-cdimage=` option doesn't set one flag in the config, which causes it to fail showing the loaded CUE image. This is easy to bypass however, by specifying that option using `-s` instead:

`-s cdimage0=<path to your cue>,image`

Notice the `,image` part in the end? If you specify that it will also show in the GUI. ;-)

**Comment by Voljega** [comment]
@midwan Well the fixx for the joystick type worked, but I still have the same problem for the CD not showing in GUI ...
`2020-05-10 11:12:26 INFO (emulatorlauncher.py:168):runCommand(): command: ['/usr/bin/amiberry', '-G', '-model=CD32', '-s', 'cdimage0=/userdata/roms/amigacd32/Litil Divil (1994)(Gremlin)[!].cue,image', '-s', u'joyport1_friendlyname=Sony PLAYSTATION(R)3 Controller', '-s', 'joyport1_mode=cd32joy', '-s', 'joyport2=', '-s', 'gfx_center_vertical=smart']`

I'm also wondering if it could be a serialization issue from python when executing the command

**Comment by midwan** [comment]
@Voljega hm, perhaps. Have you tried it manually to see if it makes a difference for you?

**Comment by Voljega** [comment]
just tried it doesn't 
` /usr/bin/amiberry -G -model=CD32 -s cdimage0=/userdata/roms/amigacd32/Litil\ Divil\ \(1994\)\(Gremlin\).cue,image`

same issue....

I repost our patch as it might be linked : 
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/amiberry/000-amiberry-path.patch

don't know if this might be an issue, but as we put `data` icon dir into '/usr/share/amiberry' I have to move into this directory before launching the command, otherwise the GUI crash because it doesn't find the cursor...

don't know if it's related but between the patch and that, I can't see what it is , better leave no stone unturned ;)

pretty sure this issue and the one about floppies are linked though
