### ISSUE TITLE
Missing version check when updating "WHDLoad Database/XML"

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#640]
System: Raspberry Pi 4 with RetroPie 4.6 and Amiberry Version 3.4 beta 8

If the existing version was already up-to-date when "Update WHDLoad Database / XML" was executed, a corresponding note has so far always been shown and not updated. Updates of the "WHDLoad Database / XML" were therefore only carried out if the existing version is older.

It has recently changed. Now the existing file is updated every time "Update WHDLoad Database / XML" is executed.

I therefore ask whether there is no longer a version check.

Cheers
Retro1968

**Comment by midwan** [comment]
No, the version check is skipped.
The latest file was always downloaded first, then checked for the version
string, and finally copied over.

Since the download occurs anyway, there's little point in checking the
contents of the file before copying it to the right location, so we're just
doing that directly instead, from now on.

The version is still checked in the background and written to the log, if
logging is enabled. But the file is always copied.
