### ISSUE TITLE
Build for 64bit distro on Odroid Go Advance doesn't launch

### ISSUE THREAD

**Issue by christianhaitian** [midwan/amiberry#675]
**Describe the bug**
I build Amiberry against the go-advance PLATFORM description after making sure all necessary dev dependencies are installed.  Compilation seems to complete without issue.  When I load the generated 64bit Amiberry on a 64bit distro (TheRA Ubuntu), it states that there is a SDL Error: No available video device.  I even tried to install the required packages to run the install and still the same result.

**To Reproduce**

As root,
apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libxml2-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev
git clone https://github.com/midwan/amiberry.git
cd amiberry
make clean
make -j2 PLATFORM=go-advance
./amiberry

**Expected behavior**

Load amiberry

**Screenshots**
![image](https://user-images.githubusercontent.com/22970448/89127111-15eb4580-d4b9-11ea-926f-3717b84a1a2f.png)

**Desktop (please complete the following information):**

- OS: Ubuntu

- Version: 19.10

**Comment by midwan** [comment]
I'm afraid this is an SDL2 problem, not an Amiberry-specific one.
It needs to use a driver that will work with the platform. If none (from the enabled ones) is found, then it will fail with this message.

There was some work being done to make an SDL2 back-end driver using the `libgo2` library, that Odroid Go Advance uses. But I'm not sure how far it got, I didn't see it being merged into SDL2's main branch and I didn't see anything else related to this on any distros (yet).

Otherwise, it might work if you have X11 loaded, and it could use the X11 driver. But I don't know if that's hardware accelerated on the platform.

**Comment by midwan** [comment]
Closing this, since we cannot do anything from our side about it.
