### ISSUE TITLE
Custom controls doesn't work

### ISSUE THREAD

**Issue by 25minutes** [midwan/amiberry#684]
**Describe the bug**
By default, Amiberry uses West button for Jump (Green), South button for Fire (Red). I'm trying to swap these two buttons via Custom controls panel and I have set:
- South: Joy2 CD32 Green
- West: Joy2 CD32 Red

The result is, the West button is working (Fire), but South button is not (nothing happens on pressing it).
BTW, just curious, why controller1 is Joy2 instead of Joy1? When I try to map the buttons to Joy1 CD32 Red/Green, the buttons have no response.

**To Reproduce**

1. Launch a WHDLoad game. For example, NewZealandStory_v2.2_1180.lha. Verify that West button for Jump (Green) & South button for Fire (Red) are working.

2. Open GUI, go to Custom controls panel and set:
- South: Joy2 CD32 Green
- West: Joy2 CD32 Red

3. Go back to game.

4. Only West button for Fire is working. South button has no response.

I have tested with two devices, and see the same result on both of them.
- Raspberry Pi 3B running RetroPie 4.5.1, connecting to CRT monitor (PAL mode 720x576). The about page shows Amiberry v3.2 beta (2020-8-5).
- Amlogic S905 device running EmuELEC v3.5 (https://github.com/EmuELEC/EmuELEC), connecting to LCD (1080p mode 1920x1080). The about page shows Amiberry v3.1.2 (2020-2-10).

**Expected behavior**
With the above setting, South button for Jump should work.

**Comment by midwan** [comment]
Can you test with the current `dev` branch please?
I've rewritten the controller handling code there, so perhaps this issue is resolved.

**Comment by 25minutes** [comment]
Sorry for the delay in response. I didn't check e-mail for a while.

I don't know how to compile from the code. If you can send me a link of the binary (for arm), I will test it.
________________________________

**Comment by midwan** [comment]
If you're running RetroPie, it gives you the option to upgrade Amiberry from source. This will update to the latest stable release, which is currently v3.3. It doesn't contain the new game controller code I mentioned, but it's worth checking that version first, before we go further.
Please keep in mind that you will also need to update your RetroPie installation as well, because with that version the command line option syntax has changed.

Both of these upgrades can be done from within RetroPie itself (RetroPie-Setup).

**Comment by 25minutes** [comment]
I don't have access to Raspberry Pi 3B at this moment. I will see if the binary from https://github.com/midwan/amiberry/releases work on Amlogic S905 device running EmuELEC.

**Comment by 25minutes** [comment]
OK. I use amiberry-v3.3-rpi3-sdl2-32bit.zip, and the binary works on Amlogic S905 device running EmuELEC.

With further test, I find "South: Joy2 CD32 Green" mapping doesn't work, but "South: Joy2 UP" mapping works, in games like NewZealandStory_v2.2_1180.lha & Turrican2_v1.7_0029.lha. 

Actually, among those Joy2 CD32 buttons, Joy2 CD32 Red is the only one that has response. Is this something expected? We should use Joy2 UP instead of Joy2 CD32 Green?

**Comment by midwan** [comment]
@25minutes 
Have you set the controller type on the port you want, to be a CD32 pad? The default would be a joystick with 1/2 fire buttons, so a mapping to a CD32 button would not work in that case. Additionally, the game should support using a separate button to Jump, instead of "Up". Not all games do that, obviously. :)

Could you provide screenshots of your Input and Custom Controls panels, please?

You mentioned two game titles, but neither of them are CD32 titles. So perhaps they don't use a second button to jump, but just the Up directional one?

**Comment by 25minutes** [comment]
I didn't change controller type. I will check the config tomorrow and get back to you.

**Comment by 25minutes** [comment]
As I don't know how to take screenshot on the S905 device (developped based on CoreELEC), I take the pictures using my phone.
![screenshot-11](https://user-images.githubusercontent.com/26299733/99753086-8f6a7a80-2b20-11eb-9182-e72128f3f5aa.jpg)
![screenshot-22](https://user-images.githubusercontent.com/26299733/99753100-94c7c500-2b20-11eb-964b-a0cfa01d565b.jpg)
![screenshot-33](https://user-images.githubusercontent.com/26299733/99753111-985b4c00-2b20-11eb-8e25-5550389dac00.jpg)

The 1st & 2nd pictures show the default settings after I launch the game (NewZealandStory_v2.2_1180.lha) . The 3rd one shows the change I make to successfully swap West/South buttons for this game.

The thing is, the games on most platforms use either West/South or South/East for Fire/Jump. However, I find that many amiga games use South/West for Fire/Jump, which is uncomfortable to me. I'd prefer to swap the function of these two buttons, but I have no idea what these buttons are actually mapped to. For example, when I launch NewZealandStory_v2.2_1180.lha, I can quickly find out West button is Jump, but I have no idea if it's a separate button, or if it's actually same as UP. All I can do with Custom controls GUI is guess and try.

Is there an easy method to find out what physical buttons are mapped to what virtual buttons, after I launch a game? For example, RetroArch quick menu gives such info clearly. It will be very helpful to understand what buttons are available in the game and what needs to be done to remap the buttons when necessary.

As for now, can I assume that the 2 games I mentioned doesn't use separate button for Jump, and what I have done to swap the buttons is the right approach?

**Comment by midwan** [comment]
@25minutes 
I'm afraid there's no easy way of knowing what controls each game will be using beforehand. Although the Amiga supported joysticks with 2 buttons, and later on the CD32 included a gamepad with more buttons, most users had a 1-button joystick as that was the most common in the marketplace. Hence, most games were designed to take advantage of that 1 button, and only some had support for an optional 2nd button (e.g. for jumping, or some special move).

CD32 games were a different story, however. Since the console came with a gamepad, all the games built for it could be sure that there are more than 1 buttons available. So in most cases, a CD32 game would (or should) support multiple buttons as input. In some cases those games were ported from their non-CD32 versions however, so that may not always be the case.

What you have mapped above is correct, if you would like to use a separate button for Up (Jump) for that specific game. As you correctly assumed, those games don't have a separate button for Jump.

I think we can close this issue then?

**Comment by 25minutes** [comment]
Thank you for the clarification. Amiga was not popular in my country and I had little knowledge about it. I'm happy we now have great emu like Amiberry so we have the chance to re-visit amiga games. Your effort is much appreciated. :)
