### ISSUE TITLE
Amiberry stop starting if JIT was activated in the settings

### ISSUE THREAD

**Issue by svk77** [midwan/amiberry#690]
Hello!
I esterday updated the Retropie, from the retropie setup menu, all installed packages - the Amiberry stop starting if JIT was activated in the settings. Just black screen. No reaction on keyboard (F12). Only reboot will help.
If JIT option is off - works fine, but slooowly of course.

**Comment by joolswills** [comment]
If you use RetroPie you should report the issue first on the RetroPie forum (providing details of your config please).

**Comment by midwan** [comment]
@svk77 
As @joolswills said, please check with the RetroPie forum first, and if the problem is not resolved we can take a look here afterwards.

**Comment by svk77** [comment]
Yes guys, my fault - I wrote in the wrong place)
I installed the latest Retropie, problem is gone. Now there was another problem: WHD games are not launched from Retropay (whdboot), previously it worked.
On this issue, I should not write here either?
Well, at least the installed system works fine (aos 3.1), i can start it from there.

**Comment by midwan** [comment]
@svk77 
No worries, this just helps reduce duplicate issues or "non-issues" as you found out.
Regarding WHDLoad games and Amiberry: 
You will need both components updated to get that to work properly, RetroPie-Setup and Amiberry.

The reason is that I updated the command line syntax in Amiberry with the latest version, so RetroPie's launch script had to be updated accordingly also. If you only have the latest version of one of them, then it won't work properly until you update the second one also (Amiberry and RetroPie's launch script).

The current version of Amiberry is v3.2.1, which you can see in the About window of the emulator's GUI. If you have an earlier version than that, please upgrade it.
Otherwise, just update your RetroPie-script (using RetroPie-Setup) and you should be ready to go.
