### ISSUE TITLE
Ghosts'nGoblins game freezes while playing

### ISSUE THREAD

**Issue by BartP223** [midwan/amiberry#696]
Hello,

I have a problem with Ghosts'n'Goblins game (WHDLoad version). The game freezes while playing.
I tried on various configurations. The effect was the same each time.

My configuration:
RetroPie v4.6.7 + Amiberry v3.2.1 on Raspberry Pi 3b+

Ghosts'n'Goblins_v1.4.lha

**Comment by midwan** [comment]
Hi @BartP223 
I've tested this in the current `dev` version, but I'm afraid I can't recreate it. At least as far as I could get in the game, it worked as expected.

**Comment by BartP223** [comment]
The problem only occurs when a .uae configuration file is created

**Comment by midwan** [comment]
Why do you need to create a .uae file for this game? What are you customizing?
Can you post the file you used here, so we can examine it?

**Comment by BartP223** [comment]
I want to configure some whdbooter options (disable intro and disable trainer).

You don't need to change any options, only need to save the configuration in amiberry. Then the problems begin.

**Comment by midwan** [comment]
@BartP223 
Confirmed.

The reason is that the whdbooter sets some options manually before launching the game, but when using a UAE config file, those options are set differently. This doesn't seem to affect most games, but in this case it makes a difference.

Until I fix this permanently, try setting the following options in your .uae file to test with:
```
cpu_cycle_exact=true
cpu_memory_cycle_exact=true
blitter_cycle_exact=true
cycle_exact=true
```
(replace the existing values, which are probably set to `false`)

**Comment by midwan** [comment]
Fixed, now the GUI will show the respective options properly, and they get saved to the config file as well.

**Comment by BartP223** [comment]
Thank you very much. Best regards!
