### ISSUE TITLE
Add audio buffer option in Amiberry.conf

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#712]
We should have a default audio buffer size option, in Amiberry.conf

**Comment by FabrizioRadica** [comment]
> 
> 
> We should have a default audio buffer size option, in Amiberry.conf

From my test on my FAMIGA distro for RPI4@1.8ghz, sound buffer is set to 2 and it's perfect for games, protracker and AmigaAMP playing mp3.
Tested with: 030@faster (perfect also on cycle exact) without JIT

**Comment by stoniemahonie** [comment]
Hi,

i would like that option too.

Im runnung retropie 4.6 on a stock rpi 3b+ and use whdload on amiberry 3.3. The option sound buffer size is set to 8 as a default in the gui. With this, every game has a sound delay of approx. 1 second. If i set it to 4, it is good. I don't know if others have that problem too, because i cannot find much discussion on this matter but there is this old issue 166:

https://github.com/midwan/amiberry/issues/166

The game alien breed is a really good example of the problem on my end. The shots fired are delayed with sound buffer size set to 8 but with 4 it is like instantly.

I looked for a long time on how it is possible to change that option globally but it seems it is only possible to make a per game save in the configuration gui. It is a workaround but it would be more convenient to have that option in the amiberry.conf.

**Comment by midwan** [comment]
This should be added in `dev` later today, if all goes well ;)

**Comment by midwan** [comment]
Implemented with d86b8f71f26f0fd74e113a75229e9153b87fb545
