### ISSUE TITLE
Parallel Port JoyStick 3 and 4 No Longer Working

### ISSUE THREAD

**Issue by Dwarfboysim** [midwan/amiberry#714]
1.  I have just noticed on both my Pi 3 and Pi 4 running AmiBerry within Retropie/Emulation Station that Joysticks 3 and 4 no longer work.  My Pi 3 was last updated on the 7th September 2020.  I cannot remember exactly which build of AMIBERRY but from memory it ended with BETA.  For the Pi 4 it is the most current release as of Thursday 5th November, 2020 with all current updated from binaries applied.

1. Launched Gauntlet 2 WHDLoad image.

2. Noticed I could not select players 3 and 4

3. Press 12 to confirm AMIBERRY configuration was correctly assigned to the 3rd and 4th joysticks.

4. Tested joysticks under an N64 4 player game and they are detected and working fine.

- OS: Retropie 4.7 image with all updates
- Raspberry Pi 3 and 4

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
Confirmed, this was last working on v3.1.3.1.
I'll look into it and get it fixed. Thanks for reporting it!

**Comment by midwan** [comment]
Narrowed down to commit 30c6d80868de907c5d70e965b58dace243e564ff - before that, it still works normally.

**Comment by Dwarfboysim** [comment]
Hi,
What does fixed in dev mean?

Thanks,
Greg

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by midwan** [comment]
@Dwarfboysim 
It's fixed in the current `dev` branch, where the beta versions are still work-in-progress, until the next stable release.
When that happens, `dev` gets merged into `master` and a new version comes out for everyone using the "normal channels", including pre-built binaries from me.

You can of course install the `dev` version at any time, by cloning this repository's `dev` branch and building it from source fromt here, as usual. If that seems too complicated, then I advise you to wait for the next stable release, instead. ;)
