### ISSUE TITLE
HDD Sounds for amiberry

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#736]
Raspberry Pi 4B, RetroPie 4.6.6, Amiberry 3.3 with AmigaOS 3.1.4.1

Hello Midwan,
I installed a new MinimigAGA core for my Turbo Chameleon 64 V1 today. Look here:
http://retroramblings.net/?page_id=1422

In addition to FDD sound, it now also offers HDD sound. For me, the HDD sound significantly increases the Amiga feeling, so I ask you whether you could also implement the HDD sound in Amiberry.

Cheers
Retro1968

**Comment by midwan** [comment]
@Retro1968 
Probably not, unless WinUAE implements this at some point.
There are too many things to work on still, in order to improve Amiberry and bring it up to the standard of WinUAE regarding emulation. I don't think implementing something like this would be a priority at the moment, especially since it would have to be done "from scratch" (in the sense that it doesn't exist in other UAE implementations).
