### ISSUE TITLE
Additional Kickstart ROM scanning paths

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#74]
The default path for kickstarts is presently ~/kickstarts

that is overwritten by: 
pandora.rom_path=  from within the .uae file.

e.g. pandora.rom_path=/home/pi/RetroPie/BIOS/Amiga/

I would request that multiple paths are scanned for the kickstart, in order:
-  pandora.rom_path= 
- ~/kickstarts
-  /home/pi/RetroPie/BIOS/ 
-  sub-folders of /home/pi/RetroPie/BIOS/  (or /home/pi/RetroPie/BIOS/Amiga)

It might need to check how $FILE_PATH is handled, if used in the configuration file and possible replace/ignore this for additional scanned paths 

This  would solve a few complaints and probably make the 'risk' of mis-aligned kickstarts much lower.

**Comment by windale** [comment]
Just out of interest, why did you change the kickstarts path to BIOS/Amiga ? Everything in RetroPie says to put the kickstarts in the BIOS directory. It would probably be easier to get RetroPie to change the SymLinks.

**Comment by HoraceAndTheSpider** [comment]
Because the latest RetroPie has much more organised BIOS folder.

This includes separated folders for Machines, PPSSPP, and capitalisation of letters.

Regardless of this, the "request" still stands- it would be better practice to check multiple folders, and fairly simple to implement.

**Comment by windale** [comment]
You don't have to sound so sarcastic in all your posts. The RetroPie BIOS folder has always been like that. There are symlinks in the kickstarts directory that point to the BIOS folder, these could simply be changed to BIOS/Amiga otherwise what's the point in them being there ?

**Comment by HoraceAndTheSpider** [comment]
It's really not my fault if you read it as sarcastic when it is not. There is very little I have commented on here.

I can post a picture of an older "messier" bios folder with othe files no longer included there if you really want, but I don't know what that will achieve. 

Anyway - on topic ; i am not saying the  symlinks cannot be changed. 

I am  just saying that doing this doesn't mean that scanning multiple folders isnta good practice and would put Amiberry in line with Fs-uae and others. 

I've already discussed this with Dimitris who asked for it to be posted here as a reminder.

**Comment by Voljega** [comment]
is it really a good idea to tie amiberry so much to Retropie though ? harcoded I mean...
uae file should be enough to specify kickstart directory

**Comment by a7mag3ddon** [comment]
It's an additional directory lookup it's not a change to anything

**Comment by osvaldolove** [comment]
It shouldn't be coupled to Retropie. 
But having it checking kickstart path in config before falling back to a default should be a valid use case.
Default on failed parsing of this setting should be **./kickstarts**

**Comment by osvaldolove** [comment]
Maybe there is scope to have a list of search paths instead, but again this should come from the .uae config and not hard coded.

**Comment by midwan** [comment]
Nothing will be hardcoded... :)

There is already support for multipath structures in the SDL2 branch, if you look in options.h:

```
struct multipath {
	TCHAR path[MAX_PATHS][PATH_MAX];
};
```

MAX_PATHS is already defined as 8, that should be enough surely?

And actually, the interesting parts we're talking about here, are already updated to be multipaths:

```
struct multipath path_floppy;
struct multipath path_hardfile;
struct multipath path_rom;
struct multipath path_cd;
```

And they are supposed to be saved like that in the config file ("supposed" because I haven't tested it much). So it's mostly a matter of a sanity check and making sure nothing gets messed up when saving / loading the info to / from the config file.

**Comment by osvaldolove** [comment]
Sounds spot on to me 👍

**Comment by windale** [comment]
Hi, I just wanted to make it known what a complete retarded arsehole this guy is, Dom Cresswell alias Horace&theSpider. He has a download link for everyone for a WHDLoad loader program that he uses on Retropie. Inside it contains all the kickstarts. I gave him a heads up about it and he deleted my post and locked the thread like a child ! 2 hours later he came back and said
Quote:
The files that have so offended your hypocracy @windale have been removed.

Perhaps you should consider why this petty behaviour is so important to you and why you feel the need to make things more difficult for hundreds of other users.

This requested change will now go to the bottom of the priority list.
What do you guys think about this ? He completely flipped because I told him that bios files were present. People purchase the Amiga Forever package to get these files legally and i'm quite suprised that osvaldolove didn't say anything about it before Dom let off another outburst !

**Comment by midwan** [comment]
@windale Please, let's keep the issue clean of any irrelevant disputes with other users
