### ISSUE TITLE
Usb joystick not working in dev 3.4

### ISSUE THREAD

**Issue by amyren1966** [midwan/amiberry#755]
In the GUI, Input, USB joystick is not available to select in the ports setup.
If I quit amiberry and launch version 3.3, the USB joystick is available for selection

This is on Raspberry Pi Os, Rpi4, when running the  december build of amiberry 3.4 beta.

**Comment by midwan** [comment]
Do you have the controllersdb.txt file in the conf directory?
It's included in the repo, but if you just compiled the binary and moved it over somewhere else for example, you might have missed it.

**Comment by amyren1966** [comment]
I actually just copied the 3.4 binary into the same dir as the old 3.3 binary and ran it.
The old 3.3 works without that conf file and did identify the usb controllers as their real identifiers, eg Speedlink Pro. 
Noe I did copy that config file from the dev folder and it does work now. But it only identifies it as PC Controller.
Are there are other files that are new in the dev version that I should copy to my amiberry folder?

**Comment by midwan** [comment]
@amyren1966 
No other new files yet, no.
This area is still under development, so expect more improvements in the coming updates. The aim is to make it work without extra hassle, the controllers file is meant to help with default mappings for unrecognized game controllers. The name of the controller it shows is found in that file, which is editable (it's just a text file). However, if you use the "Update controllers file" button from the GUI (in Paths panel), it will overwrite your own changes.

**Comment by amyren1966** [comment]
Ok, thanks for the clarification.
It definitely need some work. I have two Competition Pro joysticks. The old one is detected as Competition Pro, but the Aniversery Edition is detected as PC Game Controller, so I have edited that entry in the config file so it displays it correctly.
But the Star Traveller Gamepad is not detected, and will just result in an empty line in the port selector. So this I must find a way to add manually. But the tools listed at the gamecontroller_DB webpage does not seem to be available for the Pi.
I asume that I can not use a win PC to get these config data, since the config file have separate sections for each platform?

**Comment by midwan** [comment]
I was planning to add an option so you can create the mapping from within Amiberry's GUI. :)
There is also a command line tool from SDL2 itself, that does the same thing, but at the moment you need to compile it yourself (it's part of SDL2's sources).

If you run it on Windows, it will generate a similar entry - but I later noticed that those are not always 100% identical to the Linux versions, unfortunately. That wiki entry needs an update accordingly, but like I said: I wanted to add support for this inside Amiberry, which would make it irrelevant at the end. No external tool would be needed that way.

As mentioned above, more work is needed in this area. :)

**Comment by midwan** [comment]
94ca91f1e588a86701d5b58f0058fa4f44932468 should have fixed this now, but it needs some testing to be sure :)

**Comment by amyren1966** [comment]
I did test it now, and can confirm that my Competition Pro joystick is detected, with or without the gamecontroller_db.txt present.

But since I have added this controller already in the file, should it not use the entry from gamecontroller_db.txt instead?

**Comment by midwan** [comment]
It will if it finds it, otherwise it falls back to the old approach of using Joysticks (vs Controllers).
The difference is the way the mapping works in SDL2 - Controllers have a standard mapping that can be used, Joysticks do not (but we supply a default one in Amiberry, which might or might not work for everyone).

**Comment by amyren1966** [comment]
By "It will if it finds it", you mean that it will check the gamecontrollerdb.txt for a match first, and if there arent any it will try the old method?

If this is the intention, then I dont think its working properly.
In my gamecontrollerdb.txt I have an entry that matches my joystick, I did label this entry "Competition Aniversery".
When I run the previous 3.4 beta (28.dec) it will list this joystick as labeled above.
If I run the new 3.4 beta (23.jan) it ignores the entry from gamecontrollerdb.txt and instead identifies it as "SPEEDLINK COMPETITION PRO Game Controller for Android".
This entry is not in the txt file.

**Comment by midwan** [comment]
@amyren1966 
Sorry, I didn't explain this fully.
SDL2 has 2 methods of reading joystick information: Joysticks or GameControllers (which are still joysticks in the background, but with the added mapping found in a list of "recognized" controllers).
Up to Amiberry v3.3, we were using the Joysticks subsystem only. We provided a default mapping ourselves, to have some way of working with gamepads that offer multiple buttons, but this wasn't perfect in every case and the user would have the option to use a custom mapping with a RetroArch config (which is used in RetroPie for example).

Now with the new beta, I've added support for the GameControllers subsystem, which offers a better mapping for all the recognized controllers out of the box. However, not all controllers are recognized there, so we had the following options:
- Add an entry in the controllerdb.txt file, with a mapping for your controller
- Use a retroarch mapping like before
- Implement a fallback mechanism to use the Joystick subsystem as before, if the controller was not recognized

All of the above work, while the 3rd item was just added to make things easier (I imagine many users won't be comfortable having to edit a text file manually just to get their joystick working).

However, there are a few details in the implementation:
- The reported names from the Joystick and GameController subsystems, for the same device, are usually different
- The retroarch mapping file needs to match the Joystick name exactly, for it to be picked up (this is coming from RetroPie as it uses Joysticks, not GameControllers)

So, to keep things consistent and backwards compatible, I'm using the Joystick names everywhere, even if we have a recognized controller with the mapping loaded from there.

You can verify this yourself if you enable the logfile, and check what it mentions about the Joystick/GameController detection. If it mentions "Controller", then it was a recognized game controller, otherwise it will mention "Joystick" (and also that it wasn't found in the list of known controllers). If a retroarch mapping file was found/used, it will also mention that.
