### ISSUE TITLE
Joystick autoswitching seems to not allow for two player games

### ISSUE THREAD

**Issue by BrianGilbert** [midwan/amiberry#771]
**Describe the bug**
Switching port 0 and 1 seems to mean that I can't play two player games. I found that the joysticks need to be on port 0 and port 1, would it make sense to move the switching functionality to be between port 0 and port 2? or add a port 4 to switch between that wouldn't collide with 4 player games?

**To Reproduce**

1. Set port 0 to mouse, configure port 1 with joystick, and port 2 with joystick, 

2. Attempt to play 2 player game ie. Pang

3. Only one player will be able to play (pink player 2)

**Expected behavior**
When I switch between mouse and joystick for port 0, port 1 should still be a joystick device so that I am able to play 2 player games. This would mean I don't need to open the admin interface and would make it much easier for my kids to play games.

**Screenshots**
This screenshot shows the configuration required to play 2 player games.

![IMG_8553](https://user-images.githubusercontent.com/114017/108274229-b6d8ee00-71c8-11eb-8356-4aa73aed6f9d.jpg)

**Desktop (please complete the following information):**

- OS: Raspberry Pi OS

- Version from PiMiga 400 1.5

**Comment by BrianGilbert** [comment]
if this is just misconfiguration, pleae let me know the correct way to do it. thanks.

**Comment by midwan** [comment]
I'm afraid that won't work.
The Amiga had 2 9-pin ports, represented here by Port 0 and Port 1.
The system mouse was always expected to be connected in Port 0, and usually a Joystick in Port 1.
If you wanted to play 2-player games, you had to swap out the mouse with another Joystick in Port 0.

Ports 2 and 3 were only possible at a later point, by using a Parallel port adapter - but only certain games supported that.
Most games will only work with the Port 0/1 combination, as described above.

**Comment by midwan** [comment]
There still seems to be something wrong with the implementation of this feature, so I'll be taking another look at it...

**Comment by BrianGilbert** [comment]
@midwan trying to clarify the issue from my perspective, I think there needs to be a virtual port that is used to swap with port 0, this would allow for a joystick on port 0 and 1 at the same time allowing for 2 player games without entering config screen while in emulation.

At the moment I have to ignore the auto switching functionality and configure a jsytick on both port 0 and port 1 to be able to play a 2 player joystick based game.

**Comment by midwan** [comment]
@BrianGilbert 
This seems to work as expected in the current version, after doing some tests.
Here's what I tried, in case in helps (or in case you're trying something different):
- Loaded up a config to boot AmigaTestKit.adf, so I can easily see what's happening in the mouse/joystick ports
- In my Input panel, I had port 0 set to Mouse and port 1 to one of my joysticks
- I had 2 joysticks and 1 mouse connected on the device, during this test.
- In AmigaTestKit, I went to Mouse/Joystick/Gamepad test
- I tested moving and pressing fire on the Joystick port - as expected, I got the relevant boxes to light up
- I tested moving the mouse and saw the Mouse port show the relevant updates
- Then I pressed fire on the 2nd joystick, which swapped the mouse with that on port 0. Again, this was the expected behavior.
- Changing AmigaTestKit option for the 1st port to Joystick, allowed me to see the directional and fire buttons as I pressed them.
- I clicked the mouse button and it switched back to Mouse for port 0, as expected.

Therefore I think this is working properly, at least with the current version from `master`.
Let me know how it works for you, if you get a chance to try it out again after updating.

**Comment by Latruffy** [comment]
Hello @midwan ,
reading this post make me think it could solve an issue I'm encountering :
I'm currently running RecalBox 7.2 on a RPI 3B+, that is to say using Amiberry 3.3 if I'm not wrong.
Wanting to run some 2 players games, I've plugged and setup the uae config file with 2 joysticks respectively on port0 and port1.
Unfortunately, launching the rom often starts by a little "demo" (you see what I mean...) requiring to click mouse button on port0 to get infinite lives, ammo,.. and finally to leave.
I'm desperately  trying several configurations, no way to get what I want, which is, to sum up, raspberry dynamically accepting configuration of both a mouse and a joystick on port0.
(just for the story, when I owned a real A500 30 years ago (I know, you're thinking "no, I'm dealing with a prehistoric man..."), I was using a "Y cable with a switch" of my own on port0, with mouse plugged on one side and joystick on the other, working perfectly !!!)
Then, could you please tell me what is exactly the Amiberry version you're dealing with when talking about master branch at the date of your post ?
Do you think it may solve my issue on my RPI ?
And finally, could you please explain where to download this AmigaTestKit.adf, or share it ?
Thanks very much by advance.
Regards

**Comment by midwan** [comment]
@Latruffy 
I was referring to the current version in the `master` branch, which is 4.1.5 RC4 at the moment. This will eventually become the v4.1.5 release, once testing is finished.

There are binaries available on the releases page (https://github.com/midwan/amiberry/releases), but only for some of the supported platforms. Unfortunately I don't have every possible platform/hardware configuration available here, to provide binaries for all. In all other cases, you need to compile it from source, using the instructions in the Readme file.

Recalbox is probably a special case, as you don't have any compiler tools available on the distro itself from what I remember. In that case, it's the maintainers of the distro that need to take care of upgrading to the latest version, and providing that to the users.

**Comment by midwan** [comment]
@Latruffy 
And yes, that option does exactly what you're trying to achieve. Automatically switch from Mouse to Joystick (and back) on Port 0, depending on what device you "clicked".

**Comment by Latruffy** [comment]
@midwan 
Great news ! Thanks very much. You're giving me hope.
I'm gonna contact Recalbox maintainers to check if they may soon include the next Amiberry version.
Otherwise, I'll perhaps try to compile it by myself if I succeed finding available time, even if I have never compiled a program.
Thanks a lot, and have a nice day.
Regards
