### ISSUE TITLE
Alt-tab 'tries' to return to the host (?)

### ISSUE THREAD

**Issue by Gerbinist** [midwan/amiberry#776]
- Raspberry Pi 400
- Raspberry Pi OS
- Linux PI400 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
- DispmanX

Bit unsure what happens here, so I can only describe what I'm seeing visually.

I have my WB configured with [altabber](http://aminet.net/package/util/cdity/Altabber) to cycle screens with Alt-Tab. This has worked fine before, but when pressing Alt-Tab with the latest dev version, I'm seeing the mouse pointer from the host OS appearing. When clicking somewhere on WB, this mouse pointer disappears and becomes the Amiga native mouse again. But somehow the Amiga WB screen is not "in front" anymore and lost its focus, i.e. I cannot select an icon for instance and need to quit Amiberry through the menu (F12).

**Comment by midwan** [comment]
@Gerbinist 
That is currently "by design" and was added rather recently in the BETA. Though of course, it's not very useful in Dispmanx targets, since you can't really see/return to the Linux side of things (Dispmanx opens a display and takes over the whole screen, you can swap back and forth). It can be useful in Desktop environments where you might want to switch over to the Linux side quickly.

Perhaps this should become optional instead, otherwise you won't be able to use AmigaOS apps that might expect those shortcuts as you discovered.

Thanks for bringing it up!

**Comment by Gerbinist** [comment]
Great, confirmed working properly again from within AmigaOS.
