### ISSUE TITLE
Performance dropped v.3.4-4.0 vs. 3.3

### ISSUE THREAD

**Issue by Nasedo73** [midwan/amiberry#782]
The best example of dropped performance is demo "LOVE" (AGA). WHDLoad version (from PiMiga 1.5)
Amiberry 3.3 - works well, no sound issues.
Amiberry 3.4 beta / 4.0RC - sound issues from very beginning. Biggest sound problem is after image of "Bloody Marylin Monroe", it's clearly visible.

(I do realise there is a solution for this, start emulator as 040, use non-WHDLoad version - but I wanted to provide clear and easy proof supporting my statement).

Game: Chaos Engine (AGA), WHDLoad (from PiMiga 1.5)
Amiberry 3.3 - works well, starts every single time.
Amiberry 4.0RC - always stops on "loading" screen.

Chaos Engine (AGA) - ADF version. Started from DF0:
Amiberry 3.3 - no problems at all.
Amiberry 4.0RC - sound offset about 1 second.

OS: Raspberry Pi OS - tested on both versions, full and lite. 
Kickstart 3.1, ClassicWB based on WB 3.1 - platform RPi400.
Configuration based on config from PiMiga 1.5 (68030 JIT, 68882 FPU JIT, AGA, RAM 8/128)

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by Nasedo73** [comment]
Thanks for your reply.

1. When I tested Chaos Engine (AGA) I used "my standard settings" as mentioned earlier as well as standard A1200 config. Result is similar.

2. When I tested WHDLoad version of Chaos Engine, config mentioned above has been used for 3.3 and 4.0RC. As same file, with same system based on ClassicWB, with same settings giving different results, I believed it will be worthy to give it as example.

When I described problem related to demo "LOVE" (AGA), I knew solution how to make it work properly - but this example is clearly showing us differences between 3.3 and 4.0 and this could be easily recreate.

**Comment by Nasedo73** [comment]
I conducted one more test, just for Chaos Engine AGA WHDLoad version (same system, same files)

Amiberry 3.3 (68030 JIT, 68882 FPU JIT, AGA, RAM 8/128) - works like before, no problems at all.
Amiberry 4.0RC works only 68020, no JIT, no FPU, 14MHz, (more compatible x2), AGA, RAM 8/128
Using this configuration for Amiberry 4.0RC not experiencing any problem with this game, no sound offset. WHDLoad starting well, every time.

As I said before, for many problems will be a solution - but when we comparing different versions of Amiberry, we may want to ask a questions - why it works before? Was emulation of 68030 better before or maybe not accurate, and now 68030 works as suppose to?

**Comment by midwan** [comment]
The general rule is that each new version brings higher compatibility and more features that might not exist, or not work before.
For example in v4.x we have Cycle-Accurate 68000 emulation, improvements in the custom chipset emulation, improvements and bug fixes in the CPU emulation etc.

In some cases, this might cause a slight performance loss compared to older versions (e.g. when we implement more JIT functions, which before didn't exist or didn't do anything). That is expected and unfortunately cannot be avoided sometimes.

Games in general are not meant to run with JIT, or very fast emulated CPU speeds, as that will cause unexpected behavior in most cases. It can be OK in some cases, of course - it depends on the game/application/demo. If a certain game expects a specific CPU speed or synchronization with the chipset (usually due to badly written code), then it will go haywire when it finds itself in a different environment.

I still haven't tested the above, but I'll see what I can find when I do. :)

**Comment by Nasedo73** [comment]
Small update:
Amiberry 4.0RC (68030 JIT, 68882 FPU JIT, AGA, RAM 8/128 or 512) - works in one condition. We have to change:
CPU Speed from Fastest to 25MHz.
Obviously system will start and will be working slower - but this time Chaos Engine AGA (WHDLoad) version works fine, no issues.
I do believe for some reason in Amiberry 3.3 setting CPU Speed as Fastest wasn't a problem.
I do believe amount of information provided by me should be sufficient.

**Comment by midwan** [comment]
I've done some tests now, so here are my results so far.

As expected, when launched using the whdboot feature all cases mentioned above worked fine.
I did notice a small lag in the audio in Chaos Engine, which was fixed when I reduced the audio buffer from the default value of 8 to 5. You can experiment with that to see what's the best option for you (smaller number means smaller buffer, but less latency. You may have audio drop-outs if the buffer is not filled in time).

Running them under a full workbench, with CPU settings maxed out (JIT, Fastest Possible) did have glitches - but again, that's expected in most cases. Some things work fine regardless (e.g. the Starstruck demo), others will not.

As I explained above, setting the CPU speed to Fastest possible means that it will take all the available time to emulate more CPU cycles, leaving less time for custom chipset emulation. Works great if you don't need the custom chipset (e.g. on a P96 workbench), but it's not meant/ideal for games/demos.

Older Amiberry versions might have behaved differently, because as I mentioned above, we implement more accuracy on each update. For example, to implement the 68000 cycle accurate option, we lost some performance because we had to remove cache preloading of the next CPU instruction in ARM. There's always a cost...

There is a solution that I can recommend however. You can use the `uae-configuration` command line tool from within AmigaOS, to change emulator settings on the fly. You can disable JIT and set CPU speed to 25MHz before launching a WHDLoad title, then restore them when it exits back to Workbench (using WHDLoad's startup and shutdown scripts). The `uae-configuration` tool is part of WinUAE's "Amiga Programs" archive, which is included in the download. It also works fine in Amiberry.

**Comment by Nasedo73** [comment]
Thanks for your reply. I totally understand all changes, I understand they are necessary. If we would like to have a maximum compatibility - we have to change settings, adapt them to environment we emulating.
Reason behind my tests and opening this issue was just inform you about results, which may be or be not beneficial for further work towards most stable final release of Amiberry.

Maybe this is not an option for everyone, but I'm planning to keep version 3.3 and use it alongside with version 4.x and finally I want to ask a question related to version 3.3
There's one option I would like to have in version 3.3 - right control as right Amiga - is there any chance you could implement it in version 3.3?

**Comment by PandTomB** [comment]
You may look what are the differences between the Amiberry core components and UAE4ARM core components. UAE4ARM can handle Love-Demo (AGA) without frameskip (but using fast copper) and there are no graphic glitches or sound issues.

**Comment by midwan** [comment]
@PandTomB 
It also works fine in Amiberry, if you use the right configuration. I believe the issue is only happening when you run it from within Workbench using full CPU speed (with JIT enabled, Fastest possible mode).

**Comment by andiweli** [comment]
I can confirm the performance drop.
Using Workbench the mouse arrow has significant lower FPS when moving around, also opening windows on Workbench is sluggish now.

Playing clickBoom's QUAKE was excellent on 3.3 (640x400) but has visible lower performance on the same settings on 4.2.1.

**Comment by midwan** [comment]
Regarding the slower mouse movement under RTG (I'm assuming on 1080p 32-bit?), you can try enabling the Virtual Mouse driver option under the Input panel. Save your config and restart the emulator to apply the changes, as it cannot be changed on the fly.

That will change how mouse movement events are handled, and it's usually much faster and smoother. But keep in mind that some Amiga applications might not be happy about it.

**Comment by midwan** [comment]
Please test with the latest from `master`. I've brought back the multithreaded drawing routine, but this time it's an option in the Chipset panel (so it can be disabled if it causes glitches, which was the reason it was removed in the first place).

There's also a global default option for it, in `amiberry.conf`: default_multithreaded_drawing= <yes/no> to control the behavior. The relevant Wiki page will be updated shortly to reflect that.

This option, in combination with the right Audio buffer settings (e.g. Pull with a setting of 6), made the Love demo run normally under a full Workbench with JIT/040/Fastest possible, similar to what Pimiga used.

**Comment by midwan** [comment]
Fast Copper performance was improved with 2cb64ad78dc926493e4277e8166fdfe490e845bc
I think this, in combination with the previous commit mentioned above, help bring back significant part of the performance lost between the versions...

**Comment by Gerbinist** [comment]
Hi midwan, the previous changes did not impact the 'slugggish' behavior of the mouse I mentioned in this report, but the last change finally caused it to reach "normal" levels again, thanks!
