### ISSUE TITLE
Amiberry Not working

### ISSUE THREAD

**Issue by venkman383** [midwan/amiberry#828]
Hi.. I was wondering if someone can help as im properly stuck. I have Retropie running Amiberry on a RP4. It was all working fine and i could load via ADF or Whdload which worked and ran okay. Now i cant get the start amiberry screen up where you choose disks, configs etc. I can press f12 and it appears though but still wont load any games no matter which configs i choose. The whdload games also dont work and come up with a blank white or black screen. I have reinstalled from source and binary and still cant get anything to work. Any help would be greatly appreciated. Kind regards

**Comment by midwan** [comment]
Do you have valid kickstart roms installed?
Can you do the following test:
- Start up Amiberry without any config
- Select an A500 or A1200 option from Quickstart
- Press Start

Do you get to the Kickstart screen when you do that?

**Comment by venkman383** [comment]
Hi.. No cant do any of that. I have the list of games on Retropie amiga system menu.. With start Amiberry at the top. If i select start amiberry the screen just goes white. However, if i press f12 on the keyboard the amiga/amiberry config screen comes up where you can load upbthe disks change the config etc.

From the restropie amiga menu, some games load straight off but not many. Is a bit weird as used to work fine beforehand.

**Comment by midwan** [comment]
When you select Start Amiberry at the top of that list, it will start it with no config and should present you with the GUI.
Do you have any config named "default" (actual filename would be `default.uae` in the list? If so, that gets automatically loaded on startup, and perhaps it causes some of your issues. In that case, try deleting it...

Otherwise, after starting up the emulator (which should get you to the GUI screen, as I mentioned above), try going into the Paths panel and clicking on the Rescan button once. That will re-scan your Kickstart ROMs and re-save the internal Amiberry settings.

After that, try going to Quickstart, selecting A1200 from the dropdown list, then clicking on Start. Does it show the (animated) A1200 Kickstart screen?
