### ISSUE TITLE
Make savestates location configurable

### ISSUE THREAD

**Issue by redm123** [midwan/amiberry#872]
**Is your feature request related to a problem? Please describe.**
I'm unable to use Savestates. I can save, but is has no effect. Can't load, see no screenshot, can find no saved file. I also don't see any meaningful log.
Assuming that the feature generally works, that may have something to do with how Amiberry is run under Recalbox.
I tried creating "savestates" and "screenshots" directories in various locations, but this did not help.
I vaguely remember having read something that Amiberry saves them to the binary directory. Which in my case is /usr/bin, and thus read-only. Which could explain this...

**Describe the solution you'd like**
A path config parameter like for the other paths (roms, config, log, retroarch)

**Additional context**
Amiberry 4.1.5
Recalbox 8.0

**Comment by midwan** [comment]
This is already implemented in the latest version from `master` (which will become the next reelease, v4.2).
All paths in `amibery.conf` are now configurable and you can even override them with command line parameters on startup.

Otherwise, in previous versions (up to 4.1.6) the path was expected to be in a `savestates` directory, under the startup location of the binary. If that directory doesn't exist, or if you don't have read/write access to it, Savestates won't work.

**Comment by redm123** [comment]
Oh, bad timing for the report it seems, but at least I wanted to try it with that 4.1.5 first ;) 
But cool, great to know!
Then we can close this one, I guess.
