### ISSUE TITLE
first start BLACK SCREEN no GUI (pi400)

### ISSUE THREAD

**Issue by pi400user** [midwan/amiberry#885]
hi there !
im old amiga fan.
im new in PI400. Amiberry  4.1.6 dmx 32 bit wont start. NO GUI at all. Black screen. System hangs up.
Fresh System after update and apt with all packcages also.

SDL version goes without problems.

PI400 :
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
Linux raspberrypi 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux

**Comment by midwan** [comment]
This is most likely due to the default gfx driver in bullseye - it switched from `fkms` to `kms`, which disables the Dispmanx back-end completely.

If you change it to `fkms` again, it should work as expected.

**Comment by pi400user** [comment]
thx. it works !!!

Dimitris Panokostas ***@***.***> schrieb am Sa., 22. Jan.
2022, 17:58:

**Comment by pi400user** [comment]
why documentation is so poor. no info before download.

Dimitris Panokostas ***@***.***> schrieb am Sa., 22. Jan.
2022, 17:58:

**Comment by pi400user** [comment]
is big difference in performance between sdl and dmx version ?

Dimitris Panokostas ***@***.***> schrieb am Sa., 22. Jan.
2022, 17:58:

**Comment by midwan** [comment]
On 32-bit RPI-OS, the DMX version will probably be faster.
On 64-bit distros, which include newer SDL2 versions as well (e.g. Manjaro), the SDL2 version is about equally fast.

**Comment by amyren1966** [comment]
I had the same issue here now.
Since Raspberry Pi OS have gone 64 bit now, I think there is no reason for me to hold on to Manjaro.

Compiling with: 
make -j2 PLATFORM=rpi4-64-dmx
gave a black screen when launcing amiberry. Only the mouse pointer is visible on screen.

I tried to change the default gfx driver from kms to fkms as written above, but this option seem to be removed from Raspi-config in the latest Raspberry OS. It is suposed to be under Advanced, A2, but in that menu there is A1 and the next entry is A3.

Instead compiling with 
make -j2 PLATFORM=rpi4-64-sdl2
and it works. Although the GUI will apear in a window instead of the full screen.

I think this should be described more clear on the main page under section 'Choosing a target'

**Comment by midwan** [comment]
DMX is disabled altogether in the system, if `kms` is used. If you want to use the DMX version, you have to manually switch to the `fkms` driver, there's no way around it. Otherwise, you can use the pure SDL2 version, as you saw also. :)

Even though raspi-config may have changed, the option can still be enabled by editing the file `/boot/config.txt` directly.

The SDL2 version opens in a window by default, if launched under X11. You can change the behavior by editing `conf/amiberry.conf` and enable full-window by default, for example. Take a look at the default options in the wiki: https://github.com/midwan/amiberry/wiki/Amiberry.conf-options

**Comment by amyren1966** [comment]
Thanks for your quick reply. I have no need to use DMX version, I just started with that from old habbit.
But I just thought mentioning this on the main page would be a good idea.
People wanting to try amiberry for the first time and installs a fresh official 64 bit image and follows the instructions could get this issue. 
Spesially when reading this:  "For the Raspberry Pi platform specifically, we offer a special Dispmanx version for maximum performance", people will choose to compile the DMX version for best performance.
Most people will have no idea about what fkms or kms is or how to set it.

Like in this guy, posted e few days ago on the raspberry pi forum, https://forums.raspberrypi.com/viewtopic.php?t=329939
Look like he never figured this out, and went for fs-uae instead.

**Comment by amyren1966** [comment]
After just getting the sdl2 version working, I notice there is no audio output from amiberry. (tried HDMI and audio jack)
I did check that I do have HDMI audio from the Chromium browser on youtube.
Is there some obvious setting I have missed here?

**Comment by midwan** [comment]
> Thanks for your quick reply. I have no need to use DMX version, I just started with that from old habbit. But I just thought mentioning this on the main page would be a good idea. People wanting to try amiberry for the first time and installs a fresh official 64 bit image and follows the instructions could get this issue. Spesially when reading this: "For the Raspberry Pi platform specifically, we offer a special Dispmanx version for maximum performance", people will choose to compile the DMX version for best performance. Most people will have no idea about what fkms or kms is or how to set it.
> 
> Like in this guy, posted e few days ago on the raspberry pi forum, https://forums.raspberrypi.com/viewtopic.php?t=329939 Look like he never figured this out, and went for fs-uae instead.

I've updated the Readme to make it more clear, that `fkms` is required if you want to use DMX. It's more of an issue now with Bullseye out, where `kms` became the default setting.

Regarding the audio problem, I'm not sure - I don't believe I've run into something like that before. It usually "just works" with the default settings, and I've even added the option to choose your sound card (in case you have more than the built-in RPI hardware, like a USB one).

**Comment by solskogen** [comment]
I've added this problem to the FAQ

**Comment by amyren1966** [comment]
Audio problem resolved. It was just a basic thing, that new option you added turned out to be set to SDL analog for the game I tested. I dont know why I didnt get any sound from the headphones though. But setting it to sdl digital made the HDMI audio work.

**Comment by pi400user** [comment]
and why not amiberry just say  "you dont have poperly gfx driver". i bacame
only black screen.

Dimitris Panokostas ***@***.***> schrieb am So., 27. Feb.
2022, 13:16:

**Comment by midwan** [comment]
Because it's not possible for Amiberry to know what setting you have on your system.
