### ISSUE TITLE
Worthy add to database

### ISSUE THREAD

**Issue by danko79** [midwan/amiberry#924]
It's possibile add to DB Whorty game?
https://pixelglass.org/#worthy

**Comment by midwan** [comment]
@HoraceAndTheSpider can you look at this?

**Comment by danko79** [comment]
Are you talking about Amiberry XML Builder? I don't know how to use it can you tell me how to do it?

**Comment by midwan** [comment]
Yes, it would need a new entry there, with the relevant checksum value, name, and related options. You can open up the XML and see how the entries look like, as an example. Normally @HoraceAndTheSpider maintains that.

**Comment by danko79** [comment]
unfortunately didn't understand how to do it can't you do it for me?

**Comment by nemo93** [comment]
The way the XML is updated (currently) require the WHD package to be downloaded from a special location. Once downloaded various checks are being done on the file in order to update the XML. I do confirm that Worthy's package is not available from that special location (please don't ask for details). 

I'll look into a way to add exception to XML but I'm not keen on doing such thing :-( Exception in coding is always prone to confusion and bugs + usually a pain to maintain.

**Comment by nemo93** [comment]
@danko79 I've created a [ticket](https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/issues/108) for adding that game and I'm looking into it. I'll need your help as I don't own the game and therefore can't test it.

**Comment by danko79** [comment]
Ok, I'm available for any tests
