### ISSUE TITLE
Joystick problem with amiberry 5.0 (2022-03-31) on RetroPie

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#928]
Raspberry Pi4B running RetroPie 4.7.11 with amiberry 5.0 (2022-03-31) with AmigaOS 3.2.1 and WHDLoad Games.

After downloading the latest amiberry source code, copying it to my "/home/pi/RetroPie" folder, unzipping it there with "unzip amiberry-master.zip", then "cd amiberry-master" and compiled the source code with "make -j4 PLATFORM=rpi4" and then changed the file rights with "chmod 755 amiberry" and then installed amiberry according to these instructions, amiberry 5.0 ran successfully for me.
https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version

However, I can't move anything in the game with my joystick. Only the fire button works in the game.
In the amiberry-gui I can navigate in the menu with the joystick. I've been using these settings trying
to solve the problem but had no success and need help.

![J1](https://user-images.githubusercontent.com/58906142/161428786-8b7fdb2b-138e-46c9-a953-d67f03e90e67.jpg)
![J2](https://user-images.githubusercontent.com/58906142/161428789-576c7932-e849-4a67-926f-a27c9c197f32.jpg)
![J3](https://user-images.githubusercontent.com/58906142/161428794-3c4d56f5-2cdc-4ccf-93ef-b97ae3a15fbf.jpg)
![J4](https://user-images.githubusercontent.com/58906142/161428797-694dc919-7124-4231-9835-c74d701f926c.jpg)
![J5](https://user-images.githubusercontent.com/58906142/161428799-7d684016-de69-438d-a53d-7b2a20619560.jpg)

**Comment by midwan** [comment]
Did you add a mapping through EmulationStation when RetroPie started up? It should use that same mapping in Amiberry.

**Comment by Retro1968** [comment]
I can't say for sure now. Before that I was running amiberry 4.1.6 which I updated. In the meantime I have restored my SD card backup with version 4.1.6; also because of the auto crop problem. But as soon as there is a solution, I will gladly use amiberry 5.0 again. 

Thank you Dimitris for your great work for the Amiga community!!!  :-)

**Comment by midwan** [comment]
In my tests, it seems to work normally with controller mappings from retroarch.
I would recommend you try removing all custom controls that you seem to have set there, and starting like that (after confirming that the mapping works in other cases in Retropie also!).

**Comment by Retro1968** [comment]
Today (2022-04-10) I installed the new version (DMX: Auto-Height fixes) manually in RetroPie.

I still haven't managed to get the joystick to work. For the first time I tried to solve the problem with the remap function, too.

I'm just very surprised about this problem, because I've been using amiberry with my joypad under RetroPie for years and never had any problems with it.... until version amiberry 5.0.

I just can't find a solution and it's really frustrating me.

**Comment by Retro1968** [comment]
I am sending you my config files "MY-POWER CO.,LTD. USB Joystick.cfg" and "MY-POWER CO.,LTD. USB Joystick.cfg.bak" from the folder ~controller in "/opt/retropie/emulators /amiberry".

The backup file is slightly larger than the main file. It was probably created automatically at some point.

[MY-POWER CO.,LTD. USB Joystick.zip](https://github.com/midwan/amiberry/files/8459200/MY-POWER.CO.LTD.USB.Joystick.zip)

**Comment by Retro1968** [comment]
Maybe the problem has something to do that the joystick movements have to be assigned as DPAD movements.

**Comment by midwan** [comment]
OK, let's take it from the top:
- Which controller are you using? You provided 2 files above, but are you using both? Or one? Which one?
- Does the same controller work otherwise in RetroPie? Can you navigate the EmulationStation front-end, launch other emulators, and does it work as expected there?
- Does it partially work? Meaning, do some actions work, while others don't? If so, which ones?
- Did you add any custom controls on top, or not?

**Comment by Retro1968** [comment]
>     * Which controller are you using? You provided 2 files above, but are you using both? Or one? Which one?
I can't tell you exactly which file is used by amiberry.

amiberry 4.1.6 has these entries in the GUI and works perfect:
Input->Port 1: PS3 Controller
Custom controls -> Input Device: PS3 Controller

amiberry 5.0 has these entries: 
Input->Port 1: PS3 Controller
Custom controls -> MY-POWER CO.,LTD. USB joystick


when I select "Remap" in the menu under amiberry 5.0, this comes up:
Input->Port 1: MY-POWER CO.,LTD. USB joystick
Custom controls -> MY-POWER CO.,LTD. USB joystick


>     * Does the same controller work otherwise in RetroPie? Can you navigate the EmulationStation front-end, launch other emulators, and does it work as expected there?

Yes, no problems there.

>     * Does it partially work? Meaning, do some actions work, while others don't? If so, which ones?
 
In amiberry 4.1.6 it works perfect. In amiberry 5.0 i can navigate in the GUI with my "Arcade Fighting Stick". Up, down, left, right works here. In games only firebutton works.

>     * Did you add any custom controls on top, or not?
Yes i have a second joystick that runs over a "e4you e4you Retro Fun.cfg" and is not selected in amiberry.

**Comment by Retro1968** [comment]
Under amiberry 4.1.6 I had to select in GUI "Input->Port 1: PS3 Controller". If I then changed the entry left of "Remap" from "default" to "Joystick", I didn't had to make any more entries under "Custom Controls". The "Arcade Fighting Stick" then worked automatically perfect.

**Comment by midwan** [comment]
You shouldn't have to make any changes in Custom Controls in v5 either, nor do you need to do a Remap for you controller, if you are already using RetroArch mapping (which RetroPie asks you to configure the first time you boot it up). If you _have_ run the Remap, it would have created a new entry in the `controllers/gamecontrollerdb_user.txt` file, which might interfere with your retroarch mapping.

If so, please remove that extra line. If you're unsure, you can instead replace that file with the default one provided in the Amiberry repo.

The naming difference is OK and expected, as Amiberry will show you the Controller name (if this is recognized as a controller) in the Input tab, and the Joystick name in Custom Controls. RetroArch always uses the joystick name, and creates a config file with that name. Having the same title show in the GUI there is helpful, to know which config file is being used from RetroArch. In your case, that seems to be the `MY-POWER CO.,LTD. USB Joystick.cfg`.

You mentioned an "Arcade Fighting Stick" also above. Is that the same joystick?

If the input works from it in the GUI, then the problem is in the mapping - because only during emulation, is mapping the used. In the GUI, we have some sensible defaults (up/down/left/right and Fire) that should work for most controllers out of the box.

So if we can establish that a) you don't have any custom controls configured, b) you don't have any custom mapping set up for the joystick and c) the retroarch mapping works normally elsewhere (outside of Amiberry), we can then look into the next steps.

**Comment by Retro1968** [comment]
I copied my RetroPie backup to my SD card that uses amiberry 4.1.6. Then I updated to amiberry 5.0. No remapping or other settings was done on the joystick. The joystick we're talking about all the time is the "Arcade Fighting Stick".

I then replaced the "/conf/gamecontrollerdb.txt" files with the new data from the amiberry-master folder.
Again only the fire button works.

After that I ran in the amiberry GUI "Paths -> Update Conrtollers DB" without success.

**Comment by Retro1968** [comment]
There was no "controllers/gamecontrollerdb_user.txt" in my installation, so I copied the file from the amiberry-master folder. Unfortunately, that didn't fix the error.

**Comment by midwan** [comment]
OK, let's try to see if the retroarch mapping is the source of the problem next.
Try enabling logging also, from now on - the logfile might help figure out more details. You can enable the logfile output in the GUI -> Paths -> Enable logging. Just make sure that the destination directory/file can be created there, regarding permissions.

Next, try renaming the controller's RetroArch config file that RetroPie generated for you, to something slightly different so it's not found by Amiberry. E.g. rename `MY-POWER CO.,LTD. USB Joystick.cfg` to `MY-POWER CO.,LTD. USB Joystick.cfg-bak` or something.

Then restart Amiberry and ensure that in Custom Controls, the controller name does shows `[ N ]` next to it, instead of `[ R ]`. That indicates that no retroarch mapping was found.

Then test controller input inside emulation on something, and see if it makes any difference. Please attach the logfile below, also.

**Comment by Retro1968** [comment]
I have enabled logging and renamed the file.

amiberry 5.0 now has these entries:
Input->Port 1: PS3 Controller
Custom controls -> PS3 controllers
and [N] instead of [R].

While "none" was previously displayed everywhere under Custom controls, key assignments are now displayed there.

The controller works now in WHDLoad-Games! Thanks!!!

I would like to test a little more and then I'll get in touch with you if the thread can be closed.

**Comment by midwan** [comment]
OK, this proves that the issue is related to either the contents or parsing the retroarch mapping file.

If Amiberry's the only emulator you're using there, perhaps this is good enough and we can stop here. But if not, then you'll have a problem after renaming that config file, because no other emulator in the system will use this mapping either (and they are depending on it).

It would be great to be able to recreate this here, to see what exactly is happening. You mentioned this is a custom controller build? It still seems to the normal mappings of a PS3 controller however, if it works with that default mapping for you.

**Comment by midwan** [comment]
Note: The Custom Controls show "None" if a matching RetroArch config is detected. That does not mean that there is no mapping there, it only means there's no "custom" mapping there, to override retroarch.

If no retroarch config is found, then Custom Controls shows the default mapping for the controller, and you can of course modify it.

**Comment by Retro1968** [comment]
> OK, this proves that the issue is related to either the contents or parsing the retroarch mapping file.
> 
> If Amiberry's the only emulator you're using there, perhaps this is good enough and we can stop here. But if not, then you'll have a problem after renaming that config file, because no other emulator in the system will use this mapping either (and they are depending on it).

No i use a lot of emulators on RetroPie. Just testet mame with "1941" successfully. Will test the next days more.

> It would be great to be able to recreate this here, to see what exactly is happening. You mentioned this is a custom controller build? It still seems to the normal mappings of a PS3 controller however, if it works with that default mapping for you.

I bought the "Lioncast Arcade Fighting Stick", replaced the inexpensive buttons with "SANWA OBSF-30 Snap In Acrade Buttons" and the inexpensive joystick microswitches with Cherry-D44X (= ZF D449-V3AA) microswitches. Then everything had to be rewired. That Stick rocks now. ;-)

Do you need files from me to reproduce this?

**Comment by Retro1968** [comment]
An interim report: So far the Arcade Fighting Stick has been running without errors. When starting "lr-..." emulators, the system always reports: "MY-POWER CO.,LTD. USB Joystick configured in Port #1"

**Comment by Retro1968** [comment]
I haven't found any errors so far and I think the problem is solved. Thanks Dimitris!

**Comment by spocke** [comment]
I'm running in to the same problem here with some cheap game pad. I can't move left or right but can fire. It doesn't happen on the latest 4.x but does happen on the latest official 5.x and on the dev branch. I tested this on both a raspberry pi 4 and a x86 machine both exhibit the same behavior.

I narrowed it down to happening between v4.1.6 and v5.0. If I run the remap UI I can see that it properly gets the buttons presses on the directional buttons. I tried using the same config and data files just copying the amiberry executable from v5 to a v4.2.6 directory but the same problem happens. Is there something else I can do to help out with figuring out this problem.

It couldn't find anything that sticks out when doing a diff between https://github.com/BlitterStudio/amiberry/compare/v4.1.6...v5.0 but there is a lot of changes and also I couldn't git bisect since x86 linux doesn't seem to exist on previous versions and the PI is a bit slow to compile.
