### ISSUE TITLE
[WHDLoad XML] clean up and update

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#932]
Been a while since I've updated the XML and with Amiberry 5.x new release I believe it's time for an update of that file as well. I saw already [tickets](https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/issues) opened which I will look into in the very short term. 

Yet I do have a simple question: apart for the already mentioned issues what other setting(s) should be added/removed/tweaked from the XML please? 

Some pointers perhaps: 
* any new heights (400, 432, 448, 480, 512, 524, 540) or widths (320, 352, 384, 640, 704, 720, 768)? 
* There was a bug (in **3.3**): when JIT was `True` to prevent a bug the Z2 must be set to `0` hence some Z3 has to be configured as well (if not already set). Does this still apply?
* Renaming `auto-height` for `auto-crop` instead?

I'll then raise the necessary tickets and work on them.

Thus far:

- [x] ~~`Clock=28` should be changed to `Clock=25`.~~ 
- [x] ~~`FAST_RAM=8` is now default and can be removed from XML.~~

**Comment by nemo93** [comment]
@midwan the 2 listed changes are in and I've updated the corresponding tickets. Those changes should be applied the next time the XML file will be generated which should happen once a week.

@celeritydesign there's no dumb question, no need to apologize. It's alright asking. The generic answer is that you could virtually add any setting to that file. Yet it's large enough and the more settings added the more difficult it is to maintain. I'm a bit surprised that you had to fiddle with the settings for Ork Attack. I mean it's a rather "simple" game as I recall hence I'd expect it to run flawless on Pi4. Do you have more details (or a ticket perhaps)? I'll look into that.

**Comment by midwan** [comment]
The audio settings shouldn't need to change per game. Once you find the best for your platform, you can use that as your default by setting it in amiberry.conf.
Then all games will use that setting.

**Comment by midwan** [comment]
@nemo93 
- Regarding RAM: The default is now to use 8MB of Fast RAM, which helps WHDLoad pre-load everything in most cases, and makes things even faster (no disk activity). Do we even need to specify RAM anymore? I haven't checked as many titles as you guys have, so I am just curious if we could even get rid of the Fast and Z3 settings and leave the defaults? Would that work?
- Width and Height values don't need to be fixed numbers. They can be anything as long as it's within the valid limits for PAL/NTSC. Auto-height calculates and adjusts the height based on the drawn lines, not based on a fixed list of heights, for example. Perhaps it's best to leave this to the defaults, unless a game has better known settings than that.
- I don't think we even have auto-height in the XML, do we?

Regarding Auto-Crop:
This new feature is currently only implemented in pure SDL2 versions, not Dispmanx or OpenGL. I will try to implement it there also, but since the method will have to be different it may or may not work as good. For now, those platforms still use the same-old Auto-Height method when you enable "Auto-Crop", until that time.

For SDL2 versions though, this works really well in most of the games and demos I've tested, calculating the drawn width and height based on the custom chipset output, and adjusting the blitting of the texture to the screen accordingly. For this to work, the Width/Height values _must_ be set to the default maximum (720x568) and auto-centering H/V _must_ be disabled. The option will do that as soon as it's turned on, so you don't have to worry about it, but keep that in mind. ;)

**Comment by nemo93** [comment]
* **RAM**: the only reason we'd still require to set some RAM is if the bug aforementioned is still there (JIT+Z2). I'll check that out and report back. To be clear: the logic in the XML will remain meaning one would still be allowed to set any specific RAM values should he/she chose to do so. Just no RAM value will be set by default.
* **Width and Height**: got it. I'll check that too if it still makes sense to set any fixed values in XML.
* **Auto-height**: actually [we do](https://github.com/midwan/amiberry/pull/681) :sweat_smile: I just checked as I didn't even recall that! Currently the only game it's turned on is Agony. That game does change resolution quite often between the "hi-res" intro screens and the actual game screen.

If `Auto-height` is now called after `Auto-Crop` I'll have to change the name for consistency's sake. 

I understand I won't be able to test that feature given we're still relying on Dispmanx in the current Retropie (32-bit + fake KMS). Yet I'm fine updating XML to reflect your logic as quite lots of demos/games do use `SCREEN_AUTOHEIGHT=TRUE`. 

To wrap things up a bit:
- [ ] check if the bug with **JIT+Z2** is still there.
- [ ] rename `Auto-height` after `Auto-Crop` (in XML this will give `SCREEN_AUTOHEIGHT=` > `SCREEN_AUTOCROP=`)
- [ ] check games where Width and Height values have been set. To see if those are still relevant.
- [ ] for the time being let's change the current logic only for games where `SCREEN_AUTOHEIGHT=TRUE` is set. That way:
```
SCREEN_AUTOCROP=TRUE
SCREEN_HEIGHT=568
SCREEN_WIDTH=720
SCREEN_CENTERH=NONE
SCREEN_CENTERV=NONE
```

@midwan Do you agree?

**Comment by midwan** [comment]
@nemo93 All screen-related settings are no longer used from the XML, since the bugfix #730 - those include Width/Height, Auto-Height, Centering H/V.
Those options exist as defaults in `amiberry.conf`, and they can also be overridden by using a `.uae` config file per game, if needed. 

We can discuss if there's a better way around this, but for the moment this is the current situation. :)

**Comment by nemo93** [comment]
Thanks for your response. XML cleaned up :)
