### ISSUE TITLE
make error when compiling on S905X (dietpi)

### ISSUE THREAD

**Issue by tsgiannis** [midwan/amiberry#972]
I am trying to compile Amiberry on a S905X TV box running dietpi
This error pops 
```
In file included from src/bsdsocket.cpp:18:
src/bsdsocket.cpp: In function ‘socketbase* get_socketbase(TrapContext*)’:
src/include/memory.h:657:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  657 | # define get_pointer(addr) ((void *)get_long (addr))
      |                             ^~~~~~~~~~~~~~~~~~~~~~~
src/bsdsocket.cpp:430:29: note: in expansion of macro ‘get_pointer’
  430 |  return (struct socketbase*)get_pointer (trap_get_areg(ctx, 6) + offsetof (struct UAEBSDBase, sb));
      |                             ^~~~~~~~~~~
src/bsdsocket.cpp: In function ‘uae_u32 bsdsocklib_Open(TrapContext*)’:
src/include/memory.h:763:50: error: cast from ‘socketbase*’ to ‘uae_u32’ {aka ‘unsigned int’} loses precision [-fpermissive]
  763 | # define put_pointer(addr, p) (put_long ((addr), (uae_u32)(p)))
      |                                                  ^~~~~~~~~~~~
src/bsdsocket.cpp:519:3: note: in expansion of macro ‘put_pointer’
  519 |   put_pointer(result + offsetof(struct UAEBSDBase, sb), sb);
      |   ^~~~~~~~~~~
make: *** [<builtin>: src/bsdsocket.o] Error 1
```

can you take a look ?

**Comment by midwan** [comment]
@tsgiannis 
I believe DietPi has overriding the compiler flags, at least until recently (see https://github.com/midwan/amiberry/issues/966), so either this has been fixed with a DietPi update already, or it will be. Either way, this is specific to DietPi, so please refer to them for more details. :)

**Comment by tsgiannis** [comment]
ok

**Comment by tsgiannis** [comment]
update.. .the same thing happens on Armbian jammy...so is not DietPi to blame.
I will try to update it.

**Comment by midwan** [comment]
@tsgiannis Thanks for the feedback.
It's been a while since I tested things on Armbian, but the same makefile (with the CFLAGS it uses) works normally on all the supported platforms we've tested so far (including the latest Ubuntu, macOS and Manjaro ones), so I still suspect it's something to do with the environment, in combination with the compiler CFLAGS...

Let me know if you find any more details - also, feel free to start a topic on [Discussions](https://github.com/midwan/amiberry/discussions) about it, if that's better

**Comment by tsgiannis** [comment]
UPDATE : using this FLAG : AMLSM1 allowed me to compile just fine...untested for now but it ended correctly
Take note that I have Amlogic s905X and the flag is for Amlogic S905X3 ...armbian variant is 64bit according to uname

**Comment by tsgiannis** [comment]
UPDATE #2...it works fine

**Comment by midwan** [comment]
@tsgiannis Thanks for confirming!
